### PR TITLE
Add Uninstall CTT PowerShell Profile feature

### LINKED ISSUE #2836: feat req: option to remove CTT profile.ps1
**Is your feature request related to a problem? Please describe.**
It can be tedious/annoying for users to have to manually navigate to the correct directory to remove the CTT powershell profile.

**Describe the solution you'd like**
Add an option to remove/undo/unistall the CTT powershell profile, below the existing install option in `config > powershell profile`

**Describe alternatives you've considered**
an `Undo` option similar to the `Install` tab

**Additional context**
something like this
Untitled

### PR DESCRIPTION
**Pull request by Cryostrixx**
## Contributor Note

PR status: :x: Closed
I've spent a considerable amount of time implementing this feature, and it has been sitting here for nearly three weeks without any updates. If anyone would like me to reopen this PR in the future, please feel free to @ me in the comments.
Thanks!

## Type of Change

- [x] New feature
- [ ] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [x] UI/UX improvement

## Description

Implements the ability to uninstall the CTT PowerShell Profile and all its related dependencies.

## Testing

I have tested the profile uninstallation functionality by running it in the following test scenarios:

- Baseline: Installing the CTT PowerShell Profile
- Test 1: Uninstallation of OhMyPosh dependency: [✅] Successful
- Test 2: Uninstallation of Nerd Fonts dependency: [❓] Conditional
  - Additional Context: See `Notes for Test 2` in `Additional Information`.
- Test 3: Uninstallation of Terminal-Icons dependency: [✅] Successful
- Test 4: Uninstallation of Zoxide dependency: [✅] Successful
- Test 5: Skipping uninstallation of in-use dependencies: [✅] Successful
- Test 6: Uninstallation of CTT PowerShell Profile: [✅] Successful

## Impact

- Covered by `## Description`, `## Testing`, and `## Additional Information`.

## Issue related to PR

- Resolves #2836

### New Files Created

- `$PSProfile.hash`: A file that stores the hash of the CTT PowerShell Profile; this is used to check if the profile is installed on the system.
  - Additional Context:
    - The path is derived from the `$PSProfile` variable with `.hash` being appended to the end of the file path.
    - Example Hash File Path: `C:\Users\<user>\Documents\PowerShell\Microsoft.PowerShell_profile.ps1.hash`.
    - This file will be cleaned up and removed when the CTT PowerShell Profile is uninstalled from the system.
- `$PSProfile.bak`: A file that is used as a backup of the PowerShell profile prior to the CTT PowerShell Profile being installed on the system.
  - Additional Context:
    - The path is derived from the `$PSProfile` variable with `.bak` being appended to the end of the file path.
    - Example Backup File Path: `C:\Users\<user>\Documents\PowerShell\Microsoft.PowerShell_profile.ps1.bak`.
    - This file will be moved back to the original PowerShell profile's location when the CTT PowerShell Profile is uninstalled from the system.

### Notes for Test 2

- Note 1: Nerd Fonts won't always be installed due to an issue with the setup script for the PowerShell profile.
- Note 2: If the font is not installed, the user will see the message: `===> Already Uninstalled: Nerd Fonts. <===`.

## Checklist

- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Review by ruxunderscore — APPROVED** [review]

**Review by Real-MullaC — APPROVED** [review]

**Comment by tmcnulty387** [comment]
If the profile was installed using a previous version of winutil, it will say it's already installed. This is fixed by clicking 'Install CTT PowerShell Profile' first, then clicking 'Uninstall CTT PowerShell Profile'.

**Comment by Cryostrixx** [comment]
> If the profile was installed using a previous version of winutil, it will say it's already installed. This is fixed by clicking 'Install CTT PowerShell Profile' first, then clicking 'Uninstall CTT PowerShell Profile'.

@tmcnulty387 
I understand your concern but this isn't a bug, it's how the uninstallation functionality was designed, if the profile doesn't exist it defaults to saying it is already uninstalled, here is why:
When I run `(Get-FileHash $PROFILE).Hash` on my current PowerShell profile I get `ED277A035A46B5CAF14568477B9F6107742FA99873B01CA2B627DEDB8DA3E2EB` which represents the hash of the profile at that specific point in time, the file hash is directly based off of the content of the file. when the file content is changed, so is the file hash.
However, if I install Chris Titus Tech's PowerShell profile and run `(Get-FileHash $PROFILE).Hash` again I will get a completely different value: `CE13DF5DD10B48713EE2EF6A48D98A8DA8F9E14890412F833D8FF4E430735855`, as your profile has been replaced with the new one, again changing the file content changes the file hash.
If I run `(Get-FileHash "$PROFILE.bak").Hash`, you will see it is the same hash as my original PowerShell profile since it is copied to `"$PROFILE.bak"` and restored when the profile is uninstalled: `ED277A035A46B5CAF14568477B9F6107742FA99873B01CA2B627DEDB8DA3E2EB`.
If the profile is already uninstalled the hash will not match, hence why `===> Already Uninstalled CTT PowerShell Profile. <===` is shown, this same thing will happen if you don't have a PowerShell profile as the file hash it is comparing against will be empty.
As far as I know, there isn't a way to differentiate between the profile not being installed to begin with and being uninstalled, unless another contributor steps in and knows another way to check for this, this is how it has to be done.

-----

Additionally, I would like to mention the changes I added to `Invoke-WinUtilInstallPSProfile.ps1` only do two things:
1. It saves the hash of Chris Titus Tech's PowerShell profile to `"$PSProfile.hash`" to allow for checking if it's installed or not.
2. It creates a backup copy of your original profile before Chris Titus Tech's PowerShell profile is installed on the system.
At no point does `Invoke-WinUtilInstallPSProfile.ps1` say the profile is already uninstalled, that takes place in `Invoke-WinUtilUninstallPSProfile.ps1` as shown in the following code snippet:
```powershell
# Check if profile is installed
$PSProfileHash = Get-Content "$PSProfile.hash"
if ((Get-FileHash $PSProfile).Hash -eq $PSProfileHash) {
    # Uninstall Chris Titus Tech's PowerShell profile and all its dependencies, then restore your original PowerShell profile.
} else {
    Write-Host "===> Already Uninstalled CTT PowerShell Profile. <===" -ForegroundColor Magenta
}
```

**Comment by Cryostrixx** [comment]
> If the profile was installed using a previous version of winutil, it will say it's already installed. This is fixed by clicking 'Install CTT PowerShell Profile' first, then clicking 'Uninstall CTT PowerShell Profile'.

Hello, @tmcnulty387! I'm looking into this as we speak but while I do that: Can I have some more details about the issue?
Screenshots would be a big help if I could see what buttons you are clicking, as similar behavior is happening on my end.

**Comment by tmcnulty387** [comment]
Steps to reproduce:

1. Install the CTT PowerShell Profile using stable branch of winutil (`irm "https://christitus.com/win" | iex`)
2. Attempt to uninstall CTT PowerShell Profile using this PR

step1
step2
settings_main

This can be fixed by first clicking on install CTT PowerShell Profile, then clicking on uninstall CTT PowerShell Profile, both using the PR Branch.

step3

Once restarted, PowerShell should then have default settings properly restored.

**Comment by tmcnulty387** [comment]
Thanks for fixing the issue, @Cryostrixx! I tested it again by installing the CTT PowerShell Profile using the stable branch of WinUtil (v24.10.07). I was successfully able to uninstall it by using your PR. I'm glad my report was helpful.

**Review by ruxunderscore — APPROVED** [review]

**Comment by Cryostrixx** [comment]
Check out the **Contributor Note** section for details on why this pull request was closed. In short, I prefer not to keep a PR open that is unlikely to be accepted, as it clutters the pull requests section.
As a side note, I wish there was more communication regarding PR statuses. I understand that there are multiple PRs and that it can be challenging to address them all, but it occasionally feels like contributions from more well-known contributors are prioritized over contributions from smaller contributors. Even a simple acknowledgment of a PR could greatly enhance motivation and engagement, rather than leaving it with no activity other than the fixes that get pushed to the feature branch.

**Comment by ChrisTitusTech** [comment]
@Cryostrixx Can you reopen this? I'd like to commit to the project. Sorry it has taken a while to do the merge.

**Comment by Cryostrixx** [comment]
@ChrisTitusTech Sure, but it'll take me a while as I don't have a backup, I'll request your review when it's ready.

**Comment by Cryostrixx** [comment]
@ChrisTitusTech Alright, I remade the PR, I'm on Manjaro so I can't test it myself but it did compile successfully with PowerShell Core.
Please check out #3012.

**Pull request closed without merging**
