### PR TITLE
Added Programs to the Install List

### PR DESCRIPTION
**Pull request by Inventhrice**
Hey gang!

I love using this script, and having found need to use it frequently, I thought I would throw in my hat into the ring and add some of my own! I have added Duplicati (a backup program), OpenVPN Connect (a client to connect to a VPN), KDE Connect (A program made by KDE to sync up your phone and computer), Paint.net (a image editor that I quite like!), and Oracle VirtualBox.

I have also tested the script to make sure all the packages are correct.

This is the first time I've contributed to a public repository, so I hope I have followed all the rules for contributing! If I need to change anything, feel free to let me know :) !

### CODE REVIEW

**Comment by DaEpicR** [comment]
**Virtualbox** is a good recommendation with **Microsoft Visual C++** available in the list .

**Comment by Inventhrice** [comment]
Aw crap, I just noticed a mistake. 
image
That isn't right, the choco package for KDE connect is kdeconnect-kde. I'll see what I can do with the pull request to fix that.

**Comment by Inventhrice** [comment]
Oh sweet! I didn't know github did that! That's super sick!

For context, I just pushed my commit to the branch I'm trying to pull in, and that commit was automatically added to the PR! That's super convinent, and also I can now say that it's good to go!

**Comment by ChrisTitusTech** [comment]
Winutil.ps1 is the compiled file, the changes need to happen in `config\applications.json` and the ui updates happen in `xaml/inputXML`

**Comment by Inventhrice** [comment]
Thanks for letting me know, I also did just notice the huge box at the top of `winutil` warning anyone of this exact mistake too, my bad! I also know I didn't _need_ to revert `winutil`, but I did so anyway!

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
