### PR TITLE
Adding 3 programs to the install tab

### PR DESCRIPTION
**Pull request by TakenMC**
* Prism Launcher - Custom FOSS minecraft launcher

* Gsudo - Command line program that allows you to elevate a program as admin.

* WingetUI - Graphical front end for winget, chochlatey and scoop

### CODE REVIEW

**Review by ChrisTitusTech — COMMENTED** [review]
Not sure about prism launcher remember some bad press from them. Wasn't AT Launcher considered better for Minecraft?

**Comment by TakenMC** [comment]
AT Launcher is mostly used for modpacks due to it's easy integrations with many sites.

**Comment by Allrick1** [comment]
I like MultiMC.

**Comment by TakenMC** [comment]
Multimc and prism look basically identical

**Comment by Allrick1** [comment]
Better MultiMC the policy/owner than prism.

**Comment by TakenMC** [comment]
I mean the launchers are basically the same in design and I did use both and right now I do prefer prism

**Pull request merged**
