### PR TITLE
Adds PR template

### PR DESCRIPTION
**Pull request by Real-MullaC**
This will help with making PR's easier to read based on what is happening in that PR and what issue is being resolved.

### CODE REVIEW

**Review by MyDrift-user — APPROVED** [review]

**Comment by MyDrift-user** [comment]
looking good now

**Review by ChrisTitusTech — APPROVED** [review]
Nice! A very welcome addition to cut down on bad PR requests. We have been getting a LOT of great Pull Requests and this will continue that trend.

**Comment by og-mrk** [comment]
Well done, @Real-MullaC 
Thanks for making these changes. I'ill improve the consistency across PRs when reciewing and makes the quality of PRs much better 👍

**Review by og-mrk — APPROVED** [review]

**Comment by meenbeese** [comment]
A nice change indeed but I am not sure what a `.mb` file is. Perhaps you meant to do a markdown or `.md` ?
Screenshot 2024-07-08 172531
@Real-MullaC

**Pull request merged**
