### PR TITLE
Add qalculate to applications.

### PR DESCRIPTION
**Pull request by ruxunderscore**
# Pull Request

## Qalculate Added
Requested by Dark Knightz on YouTube.

## Type of Change
- [X] New feature

## Description
FOSS Calculator app with unit conversion capabilities.

From their website: "Qalculate! is a multi-purpose cross-platform desktop calculator. It is simple to use but provides power and versatility normally reserved for complicated math packages, as well as useful tools for everyday needs (such as currency conversion and percent calculation)."

## Impact
No Impact

## Checklist
- [X] My code adheres to the coding and style guidelines of the project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Review by Real-MullaC — APPROVED** [review]

**Comment by ruxunderscore** [comment]
Thanks Mulla. <3

**Review by MyDrift-user — APPROVED** [review]

**Review by og-mrk — APPROVED** [review]
Tested it, and it works like a charm, thanks for the cool addition @ruxunderscore 👍

### Screenshot(s)
image

**Comment by ruxunderscore** [comment]
Wait. What... O.o

**Comment by ChrisTitusTech** [comment]
Not accepting any more programs at this time. We will be moving most of the "niche" programs into a button utilizing UniGetUI.

**Pull request closed without merging**
