### PR TITLE
Test 2024 04 20 2 | 7 additions to applications.json

### PR DESCRIPTION
**Pull request by misspent**
Adds:

[NetLimiter](https://www.netlimiter.com) 
[OneCommander](https://www.onecommander.com)
[Borderless Gaming](https://github.com/Codeusa/Borderless-Gaming)
[Equalizer APO](https://sourceforge.net/projects/equalizerapo)
[FreeFileSync](https://freefilesync.org)
[Elgato Stream Deck](https://www.elgato.com/uk/en/s/downloads)
[Stardock Curtains](https://www.stardock.com/products/curtains)

I couldn't test it myself because I'm new and not entirely sure what to do, but I am willing to learn and apologies if I made a mistake. Keep up the astounding work.

### CODE REVIEW

**Comment by KonTy** [comment]
@misspent most of these tools are paid and not open source. WinUtil is all about Open Source apps, not sure we should add all of these to winutil.

**Comment by misspent** [comment]
I understand what you mean, but it would be nice to have the option for those who own it. The only ones that are free are Equaliser APO and FreeFileSync. However, the OneCommander free version is extremely good. Sorry if it wasted anyone's time. I just thought it'd be nice to see them in the tool.

**Review by og-mrk — APPROVED** [review]
The newly made additions are valid syntactically, no mis-spells and typos to be found.
Good Commits @misspent 👍

**Review by ChrisTitusTech — CHANGES_REQUESTED** [review]
I don't want to add trial ware to the utility.

**Comment by ruxunderscore** [comment]
@ChrisTitusTech Does the current winutil fallback to choco for installing, if there isn't a Winget package? I wasn't sure with the dive into the code I did, if it does. (i.e. freefilesync)

**Comment by misspent** [comment]
> @ChrisTitusTech Does the current winutil fallback to choco for installing, if there isn't a Winget package? I wasn't sure with the dive into the code I did, if it does. (i.e. freefilesync)

When you first run WinUtil, I'm going to assume it installs choco or gives you the option? If so, then I assume it's a fallback in case something doesn't offer a winget. I'd also love to know, as I've not personally tested or looked into it.

image

**Comment by MyDrift-user** [comment]
> > @ChrisTitusTech Does the current winutil fallback to choco for installing, if there isn't a Winget package? I wasn't sure with the dive into the code I did, if it does. (i.e. freefilesync)
> 
> When you first run WinUtil, I'm going to assume it installs choco or gives you the option? If so, then I assume it's a fallback in case something doesn't offer a winget. I'd also love to know, as I've not personally tested or looked into it.
> 
> image

As far as i know it checks for chocolatey at the start because it is easy to install/upgrade via the shell and with it winget can easily be installed/upgrade. If you actually start the process of installing/upgrading ... an application it checks for winget.

So I would say Winget is prio for managing applications and choco is to install winget, so checked at start and additional fallback for if there is a "na" (meaning no package with winget) in the winget property.

**Comment by ruxunderscore** [comment]
> > > @ChrisTitusTech Does the current winutil fallback to choco for installing, if there isn't a Winget package? I wasn't sure with the dive into the code I did, if it does. (i.e. freefilesync)
> > 
> > 
> > When you first run WinUtil, I'm going to assume it installs choco or gives you the option? If so, then I assume it's a fallback in case something doesn't offer a winget. I'd also love to know, as I've not personally tested or looked into it.
> > image
> 
> As far as i know it checks for chocolatey at the start because it is easy to install/upgrade via the shell and with it winget can easily be installed/upgrade. If you actually start the process of installing/upgrading ... an application it checks for winget.
> 
> So I would say Winget is prio for managing applications and choco is to install winget, so checked at start and additional fallback for if there is a "na" (meaning no package with winget) in the winget property.

I made the new installing system for winget, the only time choco is used in regards to installing winget, is when you click on Fix Winget (Invoke-WPFFixesWinget.ps1) in which it force installs winget through choco, as a just in case something went wrong with your copy of winget and you already have the latest version. 

As for the call to install a program, as far as I could tell, when adding fixes for the program installation, winget is used to install anything in the applications list. Maybe we need to add another check that falls back to choco, if winget=na. We would then need to send the choco id to the install function as well, if that is the case.

**Comment by MyDrift-user** [comment]
> > > > @ChrisTitusTech Does the current winutil fallback to choco for installing, if there isn't a Winget package? I wasn't sure with the dive into the code I did, if it does. (i.e. freefilesync)
> > > 
> > > 
> > > When you first run WinUtil, I'm going to assume it installs choco or gives you the option? If so, then I assume it's a fallback in case something doesn't offer a winget. I'd also love to know, as I've not personally tested or looked into it.
> > > image
> > 
> > 
> > As far as i know it checks for chocolatey at the start because it is easy to install/upgrade via the shell and with it winget can easily be installed/upgrade. If you actually start the process of installing/upgrading ... an application it checks for winget.
> > So I would say Winget is prio for managing applications and choco is to install winget, so checked at start and additional fallback for if there is a "na" (meaning no package with winget) in the winget property.
> 
> I made the new installing system for winget, the only time choco is used in regards to installing winget, is when you click on Fix Winget (Invoke-WPFFixesWinget.ps1) in which it force installs winget through choco, as a just in case something went wrong with your copy of winget and you already have the latest version.
> 
> As for the call to install a program, as far as I could tell, when adding fixes for the program installation, winget is used to install anything in the applications list. Maybe we need to add another check that falls back to choco, if winget=na. We would then need to send the choco id to the install function as well, if that is the case.

So as of now the "choco" tag inside the applications.json is not being used?

**Comment by ruxunderscore** [comment]
> > > > > @ChrisTitusTech Does the current winutil fallback to choco for installing, if there isn't a Winget package? I wasn't sure with the dive into the code I did, if it does. (i.e. freefilesync)
> > > > 
> > > > 
> > > > When you first run WinUtil, I'm going to assume it installs choco or gives you the option? If so, then I assume it's a fallback in case something doesn't offer a winget. I'd also love to know, as I've not personally tested or looked into it.
> > > > image
> > > 
> > > 
> > > As far as i know it checks for chocolatey at the start because it is easy to install/upgrade via the shell and with it winget can easily be installed/upgrade. If you actually start the process of installing/upgrading ... an application it checks for winget.
> > > So I would say Winget is prio for managing applications and choco is to install winget, so checked at start and additional fallback for if there is a "na" (meaning no package with winget) in the winget property.
> > 
> > 
> > I made the new installing system for winget, the only time choco is used in regards to installing winget, is when you click on Fix Winget (Invoke-WPFFixesWinget.ps1) in which it force installs winget through choco, as a just in case something went wrong with your copy of winget and you already have the latest version.
> > As for the call to install a program, as far as I could tell, when adding fixes for the program installation, winget is used to install anything in the applications list. Maybe we need to add another check that falls back to choco, if winget=na. We would then need to send the choco id to the install function as well, if that is the case.
> 
> So the "choco" tag inside the applications.json is not being used at the time?

As far as I can tell, that is true.

**Comment by hamburgerghini1** [comment]
Peace GUi would be great addition for equalizerapo, sad that it's only available via scoop.

**Comment by KonTy** [comment]
> As far as I can tell, that is true.
Yes that is true, we are not using choco. winget has been pretty stable not sure why we still have choco. Maybe we should add an Option for "preferred installer" where people could chose which one to use?

**Comment by MyDrift-user** [comment]
> > As far as I can tell, that is true.
> 
> Yes that is true, we are not using choco. winget has been pretty stable not sure why we still have choco. Maybe we should add an Option for "preferred installer" where people could chose which one to use?

I that in addition to a fallback to the "non-prefered installer" would be a great addition because winget still sometimes tends to have it's problems some times on some Installations.

**Review by ChrisTitusTech — APPROVED** [review]

**Review by ChrisTitusTech — APPROVED** [review]
Looks good

**Pull request merged**
