### PR TITLE
Update DeBloat.md

### PR DESCRIPTION
**Pull request by MathieuT1508**
# Pull Request

## Title
- MS Store Apps debloat update

## Change type
- [ ] New feature
- [ ] Bug fix
- [X] Documentation update
- [ ] Refactoring
- [X] Hotfix
- [ ] Security fix
- [ ] UI/UX improvement

## Description
- Added several MS Store apps that are not in the old version

## Testing
- Tested on Windows 11/10 x64, no bugs found

## Impact
- No system damage, just uninstalled unnecessary apps

## Checklist
- [X] My code adheres to the project's coding and style guidelines.
- [X] I have performed a self-assessment of my own code.
- [ ] I have commented my code, especially in areas that are difficult to understand.
- [X] I have made the corresponding changes to the documentation.
- [X] My changes do not generate any errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by Real-MullaC** [comment]
The section of file you changed is auto generated. You will need to speak to @MyDrift-user on what to do for this.

**Comment by MyDrift-user** [comment]
Hello @MathieuT1508, and Thanks @Real-MullaC for pinging me :)
The thing you are modifying here is the autogenerated documentation for the site, meaning it will be overwritten.
The json file you will want to modify is in `winutil/configs/tweaks.json`, under the corresponding tweak.

**Comment by MathieuT1508** [comment]
ok received, but I would like to submit a pull request for the modification in winutil.ps1, or is it automatically integrated once approved?

**Comment by MyDrift-user** [comment]
winutil.ps1 is the compiled version. 
To make it easy to understand:
We have split up the code in many files. every one of them will get combined to the winutil.ps1 script that is available in the release. So if you add it to the json file and Chris merges it, it will be integraded once he decides to push a release.

**Pull request closed without merging**
