### PR TITLE
Typo Fixed in Description of "Element"

### PR DESCRIPTION
**Pull request by SHR1SHAK**

### CODE REVIEW

**Comment by og-mrk** [comment]
@SHR1SHAK This will be fixed in PR https://github.com/ChrisTitusTech/winutil/pull/2153

The dash instead of an end quote makes sense, as the description after the dash is for the Matrix (the technology which Element is using)

**Comment by SHR1SHAK** [comment]
But out the GUI it changes to "?"
Screenshot (1)

**Comment by SHR1SHAK** [comment]
Sorry, I didn't see it was already resolved. Just new to it and learning stuff.

**Comment by og-mrk** [comment]
It's ok, @SHR1SHAK 
Happens from time to time, even for the best of us 😄

**Pull request closed without merging**
