### PR TITLE
Update applications.json

### PR DESCRIPTION
**Pull request by Nikoskampourakis**
Added opera browser and yandex

### CODE REVIEW

**Comment by RocGod** [comment]
Why do we have so many versions of Opera?

**Review by Real-MullaC — CHANGES_REQUESTED** [review]
Could all applications please be put into separate PR's?

**Comment by Joanty24** [comment]
In the "Program Additions List" issue it is stated that Opera GX will not be added.

**Comment by ChrisTitusTech** [comment]
Not a chance in hell I'll ever merge ANY Opera product.

**Pull request closed without merging**
