### PR TITLE
Update missing tweaks

### PR DESCRIPTION
**Pull request by DeveloperDurp**
Noticed a couple missing tweaks as the runspace dated before the creation of these tweaks, creating PR to add those in. If you find any please let me know and I will add to the list.  

(I only see old test branches so it's sent for main for now)

- [ ] Disable UAC
- [ ] Disable Notification
- [ ] Disable TPM on Update
- [ ] Remove Cortana
- [ ] Remove Microsoft Edge
- [ ] Set Classic Right-Click Menu
- [ ] Delete Temporary Files

### CODE REVIEW

**Comment by ChrisTitusTech** [comment]
reverting all changes... way too many issues. 
Runspaces are not nearly as stable and overall give a far worse user experience. 

Which sucks because I love a lot of your code.

**Comment by ChrisTitusTech** [comment]
Going to add the `-runspace` to both xaml and main utility so we can keep working on this and give the option to run with it. I love the idea of so much of what you implemented.

**Comment by DeveloperDurp** [comment]
@ChrisTitusTech I was hoping to have a trial run before it was thrown into the main stream 😅 lol. In theory switching all the invoke-runspace commands to invoke-command would remove any runspace weirdness and will bring it back to on par with your current script but keep the config file updates. 

I'll keep working on the stability, if anything keeping the same philosophy but have the main script spin up "smaller" scripts could also be a possibility. 

I also reforked this project because github was throwing a fit when trying to merge all the changes 🤷‍♂️

**Comment by ChrisTitusTech** [comment]
Yeah I think we run it in parallel for a while. I want to adapt the main script with a lot of the structure you did.

**Comment by padsalatushal** [comment]
Hello @DeveloperDurp I want to contribute in runspace script. I can add those missing tweaks in runspace script. can you please tell me those missing tweaks. I will create pr for adding missing tweaks.

**Comment by padsalatushal** [comment]
@DeveloperDurp I notice that the dark theme option is not done yet and under config fixes: setup autologin, reset windows update, and system corruption scan is not done or maybe not working.

**Comment by padsalatushal** [comment]
@DeveloperDurp i don't know how to add dark theme enable disable in runspace and in which file we have to add those changes can you please explain me .

**Pull request closed without merging**
