### PR TITLE
Remove suspisous app from winutil.

### LINKED ISSUE #2844: Format Factory, website and download server causing ESET to warn of bad repuptation/malware, FF causes almost every antivirus to flag (See VirusTotal)
## Description Of Issue
1. When going to the FormatFactory (an app in the WinUtil software list) website, ESET Endpoint Security (latest update, aka 11.1.2039.2) interrupts the page load to warn the end user of poor/bad reputation and/or malware reports associated with the site. If the download link is clicked, the server that is contacted for the file also causes a fresh interrupt and warn. 
2. The actual FormatFactory software causes a Potentially Unwanted Program alarm on ESET upon ANY access.
3. VirusTotal reports the following after analysis of the FF installer after submitting the file via the website. 
  _(Image links to the analysis page)_
  [image](https://www.virustotal.com/gui/file/c851f2721ffad0b1ee9d9ac6d8be8a698721a86eb55b8add1bf6d6bd5a620a5c)

## To Reproduce
Perform the actions described in items 1,2, and 3 in my description of the issue.

## Expected behavior
For the above events to occur. Unfortunately, in this case I suggest removal of this suspicious software from the WinUtil application lest the WinUtil application get a bad reputation.

## Screenshots
Screenshot included above.

### PR DESCRIPTION
**Pull request by Real-MullaC**
## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [x] Security patch
- [ ] UI/UX improvement

## Description
Removes an app that has been flagged in Virus Total by a bunch of antiviruses. This was reported in issue #2844.

## Testing
No testing required.

## Impact
N/A

## Issue related to PR

- Resolves #2844 

## Additional Information
N/A

## Checklist
- [ ] My code adheres to the coding and style guidelines of the project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Review by MyDrift-user — APPROVED** [review]

**Review by og-mrk — APPROVED** [review]

**Comment by CodingWonders** [comment]
Images that prove the evidence:

vmware_umvWneEkm8
vmware_pVDY3CsTJL
1H3j7and7N
vmware_CbVRp8hXVV

**Review by CodingWonders — APPROVED** [review]

**Review by momcilovicluka — APPROVED** [review]
What they're doing is quite questionable, to say the least. Utilizing user resources in this manner is rather unacceptable. That being said, excellent catch!

**Review by ChrisTitusTech — APPROVED** [review]

**Comment by ChrisTitusTech** [comment]
Yeah this TRASH. Removed, thanks for the PR.

**Comment by rushowr** [comment]
Thanks for catching this and submitting a PR! Resolved my report as well, excellent work! Thanks to ChrisTitusTech as well for merging. Glad to see this was jumped on quickly.

**Pull request merged**
