### PR TITLE
Add the option to Block Razer automatic installs

### LINKED ISSUE #550: Feature Request: Add Block Razor script
Add script from https://christitus.com/block-razer-bloatware/

### PR DESCRIPTION
**Pull request by xicor22**
## Type of Change
- [x] New feature

## Description
Added the option to block automatic installation of razer software using the code from the chris titus original [Block-Razer repo](https://github.com/ChrisTitusTech/block-razer).

## Testing
Tested for the following cases:

- Win 11 Fresh 
- Win 11 with script used from this [repo](https://github.com/ChrisTitusTech/block-razer)

## Issue related to PR

- Resolves #550

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by Real-MullaC** [comment]
Hello @xicor22,

Thank you for your PR but this would be a tweak and not a feature. Please could this be moved to tweaks.json under the Advanced Tweaks Section.

**Comment by xicor22** [comment]
```
"WPFRazerBlock": {
    "Content": "Block Razer software autoinstall",
    "Description": "It disables the automatic driver installation and denies write permission of Razer folder to system which prevents the automatic install.",
    "category": "Essential Tweaks",
    "panel": "1",
    "Order": "a017_",
    "registry": [
      {
        "Path": "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\DriverSearching",
        "Name": "SearchOrderConfig",
        "Type": "DWord",
        "Value": "0",
        "OriginalValue": "1"
      },
      {
        "Path": "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Device Installer",
        "Name": "DisableCoInstallers",
        "Type": "DWord",
        "Value": "1",
        "OriginalValue": "0"
      }
    ],
    "InvokeScript": [
      "Remove-Item \"C:\\Windows\\Installer\\Razer\" -Recurse -Force",
      "New-Item -Path \"C:\\Windows\\Installer\" -Name \"Razer\" -ItemType \"directory\"",
      "$Acl = Get-Acl \"C:\\Windows\\Installer\\Razer\"",
      "$Ar = New-Object System.Security.AccessControl.FileSystemAccessRule(\"NT AUTHORITY\\SYSTEM\",\"Write\",\"ContainerInherit,ObjectInherit\",\"None\",\"Deny\")",
      "$Acl.SetAccessRule($Ar)",
      "Set-Acl \"C:\\Windows\\Installer\\Razer\" $Acl"
    ],
    "UndoScript": [
      "Remove-Item \"C:\\Windows\\Installer\\Razer\" -Recurse -Force",
      "New-Item -Path \"C:\\Windows\\Installer\" -Name \"Razer\" -ItemType \"directory\""
    ],
    "link": "https://christitustech.github.io/winutil/dev/tweaks/Essential-Tweaks/RazerBlock"
  }
```

I added this in the tweaks.json and got this error
image

I have the same format as other tweaks or have I missed something?

**Comment by xicor22** [comment]
I accidently put this in the essential section, lemme change that.

**Comment by Real-MullaC** [comment]
> ```
> "WPFRazerBlock": {
>     "Content": "Block Razer software autoinstall",
>     "Description": "It disables the automatic driver installation and denies write permission of Razer folder to system which prevents the automatic install.",
>     "category": "Essential Tweaks",
>     "panel": "1",
>     "Order": "a017_",
>     "registry": [
>       {
>         "Path": "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\DriverSearching",
>         "Name": "SearchOrderConfig",
>         "Type": "DWord",
>         "Value": "0",
>         "OriginalValue": "1"
>       },
>       {
>         "Path": "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Device Installer",
>         "Name": "DisableCoInstallers",
>         "Type": "DWord",
>         "Value": "1",
>         "OriginalValue": "0"
>       }
>     ],
>     "InvokeScript": [
>       "Remove-Item \"C:\\Windows\\Installer\\Razer\" -Recurse -Force",
>       "New-Item -Path \"C:\\Windows\\Installer\" -Name \"Razer\" -ItemType \"directory\"",
>       "$Acl = Get-Acl \"C:\\Windows\\Installer\\Razer\"",
>       "$Ar = New-Object System.Security.AccessControl.FileSystemAccessRule(\"NT AUTHORITY\\SYSTEM\",\"Write\",\"ContainerInherit,ObjectInherit\",\"None\",\"Deny\")",
>       "$Acl.SetAccessRule($Ar)",
>       "Set-Acl \"C:\\Windows\\Installer\\Razer\" $Acl"
>     ],
>     "UndoScript": [
>       "Remove-Item \"C:\\Windows\\Installer\\Razer\" -Recurse -Force",
>       "New-Item -Path \"C:\\Windows\\Installer\" -Name \"Razer\" -ItemType \"directory\""
>     ],
>     "link": "https://christitustech.github.io/winutil/dev/tweaks/Essential-Tweaks/RazerBlock"
>   }
> ```
> 
> I added this in the tweaks.json and got this error image
> 
> I have the same format as other tweaks or have I missed something?

This could be due to issues with tweaks currently.

**Comment by xicor22** [comment]
even though i select another tweak to get around that bug, my razer block tweak is still not getting applied

**Comment by xicor22** [comment]
```
"WPFTweaksRazerBlock": {
    "Content": "Block Razer software autoinstall",
    "Description": "It disables the automatic driver installation and denies write permission of Razer folder to system which prevents the automatic install.",
    "category": "z__Advanced Tweaks - CAUTION",
    "panel": "1",
    "Order": "a031_",
    "InvokeScript": [
      "
        function RazerBlock {
          $RazerPath = \"C:\\Windows\\Installer\\Razer\"
          Set-ItemProperty -Path \"HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\DriverSearching\" -Name \"SearchOrderConfig\" -Type DWord -Value 0
          Set-ItemProperty -Path \"HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Device Installer\" -Name \"DisableCoInstallers\" -Type DWord -Value 1
          Remove-Item $RazerPath -Recurse -Force
          New-Item -Path \"C:\\Windows\\Installer\\\" -Name \"Razer\" -ItemType \"directory\"
          $Acl = Get-Acl $RazerPath
          $Ar = New-Object System.Security.AccessControl.FileSystemAccessRule(\"NT AUTHORITY\\SYSTEM\",\"Write\",\"ContainerInherit,ObjectInherit\",\"None\",\"Deny\")
          $Acl.SetAccessRule($Ar)
          Set-Acl $RazerPath $Acl
          }
        RazerBlock
      "
    ],
    "UndoScript": [
      "
        function RazerUnblock {
          $RazerPath = \"C:\\Windows\\Installer\\Razer\"
          Set-ItemProperty -Path \"HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\DriverSearching\" -Name \"SearchOrderConfig\" -Type DWord -Value 1
          Set-ItemProperty -Path \"HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Device Installer\" -Name \"DisableCoInstallers\" -Type DWord -Value 0
          Remove-Item $RazerPath -Recurse -Force
          New-Item -Path \"C:\\Windows\\Installer\\\" -Name \"Razer\" -ItemType \"directory\"
          }
        RazerUnblock
      "
    ],
    "link": "https://christitustech.github.io/winutil/dev/tweaks/Essential-Tweaks/RazerBlock"
```

I looked at this for quite a while and cant seem to find any issues but the code in invoke script is not running. 
The previous "select a tweaks" error was caused because I didn't put "Tweak" in "WPFRazerBlock".

**Comment by MyDrift-user** [comment]
Hello @xicor22, thanks for this PR. WinUtil offers a way of easily add registry changes like in following example.

```
  "WPFTweaksRazerBlock": {
    "Content": "Block Razer Software Installs",
    "Description": "Blocks ALL Razer Software installations. The hardware works fine without any software.",
    "category": "Essential Tweaks",
    "panel": "1",
    "Order": "a007_",
    "registry": [
      {
        "Path": "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\DriverSearching",
        "Name": "SearchOrderConfig",
        "Value": "0",
        "OriginalValue": "1",
        "Type": "DWord"
      },
      {
        "Path": "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Device Installer",
        "Name": "DisableCoInstallers",
        "Value": "1",
        "OriginalValue": "0",
        "Type": "DWord"
      }
    ],
    "InvokeScript": [
      "

      "
    ],
    "UndoScript": [
      "
      "
    ]
  },
```

**Comment by MyDrift-user** [comment]
Hey @xicor22, thanks for the PR, you moved the reg changes into the invoke- & undo script again, could you please add them sepeately?

Also the Tweaks generally did not work temporarily, but should work now again. Also the function wrapping and calling kind of seems unneccessary due to it only beeing called there.

Otherwise I think it looks good :)

**Review by MyDrift-user — APPROVED** [review]
Good job, looks fine to me now 👍

**Comment by xicor22** [comment]
@MyDrift-user I'm sorry to ask you this but how do i open a new PR without the changes from this PR? I tried creating a new branch and creating a PR from that but this PR was also included in that one. I'm very new to code contribution so dont really know about this.

**Comment by MyDrift-user** [comment]
You forgot to remove the comma in feature.json

**Review by MyDrift-user — APPROVED** [review]

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
