### PR TITLE
[tweaks]: Edge Removal x86 Compat

### LINKED ISSUE #2584: New Edge removal script doesn't work with Win10 32bit
the new edge removal script doesn't work with win10 32bit. the message it gives is in the screenshot.

message

### PR DESCRIPTION
**Pull request by psyirius**
# Edge Removal x86 Compatibility (TWEAKS)

## Type of Change
- [x] Bug fix

## Issue related to PR
- Resolves #2584

## Additional Information
Pushing this from handheld device. So, sorry for the code dup. If Anyone have time rewrite it more efficient.

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by psyirius** [comment]
@MyDrift-user It might leave the shortcuts in user and public desktops. 

Could you add some lines to strip that out?

**Comment by ChrisTitusTech** [comment]
Man I feel bad as I've hit like 3 of your last PRs with the close button. 

Sadly, 32-bit support is going away and is Windows 10 Only. So adding this will just add to the code base and not needed imo. 

> As of September 30, 2024, Microsoft will no longer provide product upgrades or reinstallments for 32-bit versions of Windows 10

**Comment by psyirius** [comment]
> Man I feel bad as I've hit like 3 of your last PRs with the close button.
> 
> Sadly, 32-bit support is going away and is Windows 10 Only. So adding this will just add to the code base and not needed imo.
> 
> > As of September 30, 2024, Microsoft will no longer provide product upgrades or reinstallments for 32-bit versions of Windows 10

Alright, No more PR's from me!

**Comment by alturic** [comment]
You could always fork it to make an x86-specific version if it's going to start causing issues. Heck, this isn't even a CTT-specific issue, it's Microsoft.

**Pull request closed without merging**
