### PR TITLE
Fixed Programms names and urls and github actions

### PR DESCRIPTION
**Pull request by YusufKhalifadev**
- Fixed programs' names like f.lux to F.lux and changed a lot of URLs to programs' official websites
- Fixed Github Action I ran it locally and it worked (didn't test it on GitHub cause I don't know how to make a GitHub action)

### CODE REVIEW

**Comment by YusufKhalifadev** [comment]
I'm trying to fix unit test failing but whatever I try it seems like it's hard-coded every time it says Invoke-WinUtilGPU cannot find path 
If anybody has a solution please comment

**Comment by YusufKhalifadev** [comment]
So unit testing wasn't working because pester checks always failed
it seems like I was looking for Invoke-WinUtilGPU and Invoke-WinUtilStickyKeys functions so I fixed it by:

changing the file Invoke-WinUtilStickyKeys to Invoke-WinUtilStickyKeys.ps1
rename the Invoke-GPUCheck function in the Invoke-WinUtilGPU.ps1 file to Invoke-WinUtilGPU
after testing now everything should work and unit testing is working fine.

pester test

**Review by ChrisTitusTech — APPROVED** [review]

**Comment by ChrisTitusTech** [comment]
Looks good, going forward you don't need to include winutil.ps1 or the inputapp.xaml as those are auto-generated.

**Comment by YusufKhalifadev** [comment]
> Looks good, going forward you don't need to include winutil.ps1 or the inputapp.xaml as those are auto-generated. 

Thanks, for the approval, on not including winutil.ps1 and inputapp.xaml I didn't know how to remove them from the commit so I pushed it anyway and it doesn't conflict with the testing branch.

**Comment by ruxunderscore** [comment]
> > Looks good, going forward you don't need to include winutil.ps1 or the inputapp.xaml as those are auto-generated.
> 
> Thanks, for the approval, on not including winutil.ps1 and inputapp.xaml I didn't know how to remove them from the commit so I pushed it anyway and it doesn't conflict with the testing branch.

When you use the `git add` command you can specify files, `git add .` selects all changed files. Otherwise, you can use Github Desktop to revert changes to file and/or check only the files that you intend to submit for changes. That's the gist of it. Definitely look into the documentation or YouTube for more information on using Github.

**Pull request merged**
