### PR TITLE
add restore point function

### PR DESCRIPTION
**Pull request by munkk01**
I'm sure there is much more elegant solution than `Out-GridView` but I couldn't seem to get my tiny brain to figure something else out. 

Feel free to not use this and perhaps take inspiration for a better method.

Created in reference to:
https://github.com/ChrisTitusTech/winutil/issues/1367#issue-2074952480

### CODE REVIEW

**Comment by KonTy** [comment]
@munkk01 @ChrisTitusTech  imho this is a bit underdeveloped, this doesn't provide any additional functionality to just going to Windows and creating restore point using Windows UI. A better solution would be to have a check box in the tweaks section to create a Restore Point that could be "checked" by default and when you click "apply tweaks" it would just create it and if you don't want it you would uncheck the check box. As it is done now, it has a limited value. :-)

**Comment by munkk01** [comment]
> @munkk01 @ChrisTitusTech imho this is a bit underdeveloped, this doesn't provide any additional functionality to just going to Windows and creating restore point using Windows UI. A better solution would be to have a check box in the tweaks section to create a Restore Point that could be "checked" by default and when you click "apply tweaks" it would just create it and if you don't want it you would uncheck the check box. As it is done now, it has a limited value. :-)

Totally understandable! I just threw together something quickly to get the ball rolling and address the issue that was opened. I'm totally fine with closing this and not using it.

**Comment by munkk01** [comment]
Done deal.

**Comment by KonTy** [comment]
@munkk01 I think the opposite :-), I think we should add one more this to it (a checkbox) and push it out. If you are not familiar with WPF assign it to me, I will look at adding that logic when I have a chance

**Comment by munkk01** [comment]
> @munkk01 I think the opposite :-), I think we should add one more this to it (a checkbox) and push it out. If you are not familiar with WPF assign it to me, I will look at adding that logic when I have a chance

None of this is REALLY in my wheelhouse (I'm not a programmer and just started using git late last year). Hence the underdevelopment, incorrect usage, etc. I'm just trying to learn!

However, I'd like to try and tackle it myself for the sake of doing it. I appreciate any feedback or helpful advice. 

On that note though, I didn't realize that Chris already has a `Set-WinUtilRestorePoint.ps1` implemented and calls it in the `Invoke-WPFRunspace`. If we wanted to continue this route, would we just move that into the `Tweaks` tab itself and default it to `True` but allow users to uncheck it if they choose?

**Comment by KonTy** [comment]
> On that note though, I didn't realize that Chris already has a `Set-WinUtilRestorePoint.ps1` implemented and calls it in the `Invoke-WPFRunspace`. If we wanted to continue this route, would we just move that into the `Tweaks` tab itself and default it to `True` but allow users to uncheck it if they choose?

Good point, I don't know Chris is the ultimate decision maker but I would say so, if it was up to me, I would add a checkbox, "Create a Restore Point" somewhere close to Run Tweaks button and have it be checked by default :) and if it's checked call that function that Chris has or something. Also, thank you for doing all the work and please please keep working on this. Community is how we move projects forward and make things better for everyone.

**Pull request closed without merging**
