### PR TITLE
Feature/pester

### PR DESCRIPTION
**Pull request by DeveloperDurp**
Adding pester for unit testing

### CODE REVIEW

**Comment by DeveloperDurp** [comment]
nifty lol 
image

**Comment by DeveloperDurp** [comment]
@ChrisTitusTech The repository might need additional configuration to get actions to run properly on PRs

https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

**Comment by ChrisTitusTech** [comment]
Digging these tests. Let me know when to squash and merge. 

Adding these will help some bad PRs that will inevitably coming through.

**Comment by DeveloperDurp** [comment]
feel free to merge this in, I think I have enough for a start. It will check the config files, check the gui to ensure they match and test to see if the main script runs with no errors. I have to play around with the button clicks to ensure those work properly.

**Comment by padsalatushal** [comment]
@DeveloperDurp how can I contact you personally? Linkedin or any other

**Comment by DeveloperDurp** [comment]
links are in my profile

**Pull request merged**
