### PR TITLE
Edge removal improvements

### PR DESCRIPTION
**Pull request by MyDrift-user**
# Pull Request

## Type of Change
- [x] Refactoring
- [x] Hotfix

## Description
- added working logic to reinstall MS Edge
- added logic to remove more reg keys on removal
  - with those two reg removals edge does not give the big annoying welcome back screen but a "better" (still annoying) popup. It also offers a more clean uninstallation.
- fixed "open with" context menu having broken edge option bc MS Edge can't make a working uninstaller.
Screenshot 2024-08-08 111912

## Testing
changes were tested on vm, run & undo work without sys/ep restart needed

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by MyDrift-user** [comment]
> I had problems even with the force. I think we might have to download the EXE directly and set it up that way or use chocolatey as a backup. Need to expand the remove item property to strip out any Edge Policies if they exist.

Yeah that was the only way I was able to correctly reinstall edge without any known issues. did try that for a moment but got fed up with this message so i stopped with it for the moment, will reimplement it and commit the requested change :)
image

**Comment by psyirius** [comment]
I've personally uninstalled Edge using method in a fresh windows 24H2 install and I was able to uninstall it with all the files removed from fs as well as registry.

Check the log at `%TEMP%/msedge_installer.log` if there is smth wrong.

PS: I might raise a PR with my whole script (wip - needs spare time) to wipe edge in whatever state without the help of its setup.

**Comment by psyirius** [comment]
```powershell
function Remove-Edge {
    # Undo changes made by -> Dism Add-Edge Edge.wim
    Write-Host "$([char]0x1b)[48;2;20;14;136m=== Removing Microsoft Edge"

    reg load "HKLM\zSOFTWARE" "$mountDir\Windows\System32\config\SOFTWARE" | Out-Null
    reg load "HKLM\zSYSTEM" "$mountDir\Windows\System32\config\SYSTEM" | Out-Null
    reg load "HKLM\zNTUSER" "$mountDir\Users\Default\ntuser.dat" | Out-Null

    # Microsoft Edge
    reg delete "HKLM\zSOFTWARE\Microsoft\Active Setup\Installed Components\{9459C573-B17A-45AE-9F64-1857B5D58CEE}" /f | Out-Null

    reg delete "HKLM\zSOFTWARE\Wow6432Node\Microsoft\EdgeUpdate\Clients\{56EB18F8-B008-4CBD-B6D2-8C97FE7E9062}" /f | Out-Null
    reg delete "HKLM\zSOFTWARE\Wow6432Node\Microsoft\EdgeUpdate\ClientState\{56EB18F8-B008-4CBD-B6D2-8C97FE7E9062}" /f | Out-Null

    reg delete "HKLM\zSOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Microsoft Edge" /f | Out-Null

    if (Test-Path "$mountDir\Program Files (x86)\Microsoft\Edge" -Type Container) {
        Remove-Item "$mountDir\Program Files (x86)\Microsoft\Edge" -Recurse -Force | Out-Null
    }

    # Extra
    reg delete "HKLM\zSOFTWARE\Microsoft\MicrosoftEdge" /f | Out-Null

    # Microsoft EdgeWebView
    reg delete "HKLM\zSOFTWARE\Wow6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}" /f | Out-Null
    reg delete "HKLM\zSOFTWARE\Wow6432Node\Microsoft\EdgeUpdate\ClientState\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}" /f | Out-Null

    reg delete "HKLM\zSOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Microsoft EdgeWebView" /f | Out-Null

    if (Test-Path "$mountDir\Program Files (x86)\Microsoft\EdgeWebView" -Type Container) {
        Remove-Item "$mountDir\Program Files (x86)\Microsoft\EdgeWebView" -Recurse -Force | Out-Null
    }

    # Edge Core
    if (Test-Path "$mountDir\Program Files (x86)\Microsoft\EdgeCore" -Type Container) {
        Remove-Item "$mountDir\Program Files (x86)\Microsoft\EdgeCore" -Recurse -Force | Out-Null
    }

    # Microsoft Edge Update
    reg delete "HKLM\zSOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\MicrosoftEdgeUpdate.exe" /f | Out-Null

    reg delete "HKLM\zSOFTWARE\Wow6432Node\Microsoft\EdgeUpdate" /f | Out-Null
    reg delete "HKLM\zSOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Microsoft Edge Update" /f | Out-Null

    # Microsoft Edge Update :: Services
    reg delete "HKLM\zSYSTEM\ControlSet001\Services\edgeupdate" /f | Out-Null
    reg delete "HKLM\zSYSTEM\ControlSet001\Services\edgeupdatem" /f | Out-Null

    if (Test-Path "$mountDir\Program Files (x86)\Microsoft\EdgeUpdate" -Type Container) {
        Remove-Item "$mountDir\Program Files (x86)\Microsoft\EdgeUpdate" -Recurse -Force | Out-Null
    }

    # Prevent EdgeChromium from Installing in the future
    reg add "HKLM\zSOFTWARE\Microsoft\EdgeUpdate" /v "DoNotUpdateToEdgeWithChromium" /t REG_DWORD /d "1" /f | Out-Null

    reg unload "HKLM\zSOFTWARE" | Out-Null
    reg unload "HKLM\zSYSTEM" | Out-Null
    reg unload "HKLM\zNTUSER" | Out-Null

    Write-Host
}
```

Here is a function that removes edge from an offline windows image.

When on first boot edge sets up extra stuff like shortcuts, assocs, etc (which you can find the details in the log)

**Comment by MyDrift-user** [comment]
Isn't edge core also a compatibility layer for webview?

**Comment by psyirius** [comment]
> Isn't edge core also a compatibility layer for webview?

It's not a compatible layer. It's a shared components used by both edge and webview. (Mostly webview).

**Comment by psyirius** [comment]
Also, EdgeUpdate might not uninstall if EdgeWebview is still installed in some cases.

**Review by ChrisTitusTech — APPROVED** [review]
Looks great, that will fix a lot of edge user issue on reinstall doing it this method as well.

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
