### PR TITLE
Added pop up messages for installs

### PR DESCRIPTION
**Pull request by Real-MullaC**
Requested in issue #2116

### CODE REVIEW

**Comment by Marterich** [comment]
How does this behave for users who want to automatically apply an exported winutil config? Will this _block_ the execution of the config import and therefore require user input before any further tweaks get applied? 
If I recall correctly when importing a config, the applications are installed first.
If so, this would break the "zero touch" workflow for importing config files

**Comment by Real-MullaC** [comment]
> How does this behave for users who want to automatically apply an exported winutil config? Will this _block_ the execution of the config import and therefore require user input before any further tweaks get applied? If I recall correctly when importing a config, the applications are installed first. If so, this would break the "zero touch" workflow for importing config files

It shouldn't affect it as it was only added to say that installs are done at the end.

**Comment by Marterich** [comment]
All right, I've taken another look at the code, and I have two improvements. 

1. Move the line `$sync.ProcessRunning = $False` in front of the Popup. 
-- The installs are started in a runspace so this would block execution until the button is pressed. (This doesn't become immediately clear, because the program installed are started last when importing a config)
2. Move the Console Output in front of the Popup as well. (Also relevant for #2134)
-- With the console output _after_ the Popup, the terminal message will only be printed once the user clicks on the popup, so your order of Log-Messages in the terminal can get messed up if you wait.

**Comment by Real-MullaC** [comment]
@ChrisTitusTech I do not know how to re commit after changes to this PR.

**Comment by ChrisTitusTech** [comment]
You can move it to draft form then bring it back. 

As far as the PR, I don't think a popup is a great solution and I'm struggling to find what would be. I think the best course from here is something that changes the GUI application directly that the user is staring at.

**Pull request closed without merging**
