### PR TITLE
Add 'Zen Browser' to the Browsers tab.

### PR DESCRIPTION
**Pull request by bercedev**
just like vivaldi, brave are on this list, zen has the right to be here. although it is in alpha version now, I have not seen even 1 bug. it deserves it. please listen to my voice.

## Type of Change
- [  *  ] New feature
- [ ] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Issue related to PR

- Resolves #

## Checklist
- [  *  ] My code adheres to the coding and style guidelines of the project.
- [  *  ] I have performed a self-review of my own code.
- [  *  ] I have commented my code, particularly in hard-to-understand areas.
- [  *  ] I have made corresponding changes to the documentation.
- [  *  ] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by Real-MullaC** [comment]
This PR will not be merged as we are currently not adding any applications to WinUtil until we do a clear out of old applications.

**Comment by bercedev** [comment]
> This PR will not be merged as we are currently not adding any applications to WinUtil until we do a clear out of old applications.

as you wish, should I close this request or wait (for you to merge it when the time comes)

**Comment by MHippo** [comment]
> This PR will not be merged as we are currently not adding any applications to WinUtil until we do a clear out of old applications.

could you elaborate? does WinUtil have out of date applications on the install tab?

**Comment by ChrisTitusTech** [comment]
Not adding applications at this time and definitely not alpha or beta versions of applications.

**Pull request closed without merging**
