### PR TITLE
Fix WinUtil admin elevation for stable and pre-release builds

### LINKED ISSUE #2812: admin Elevation
## To Reproduce
1. Go to 'Run the command in a non admin shell'

### PR DESCRIPTION
**Pull request by Cryostrixx**
## Type of Change

- [ ] New feature
- [x] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [x] UI/UX improvement

## Description

Fixes the broken admin elevation logic for both stable and pre-release versions of the WinUtil script.

## Testing

I have tested the fixed admin elevation logic by running it in the following test scenarios:

### Local Tests

- Baseline: Running WinUtil without administrator permissions and without arguments.
  - Test 1: Running WinUtil locally without arguments: [✅] Successful
  - Test 2: Running WinUtil locally without arguments (as admin): [✅] Successful
  - Test 3: Running WinUtil locally with arguments: [✅] Successful
  - Test 4: Running WinUtil locally with arguments (as admin): [✅] Successful

### Remote Tests

- Baseline: Running WinUtil without administrator permissions and without arguments.
  - Test 1: Running WinUtil remotely without arguments: [✅] Successful
  - Test 2: Running WinUtil remotely without arguments (as admin): [✅] Successful
  - Test 3: Running WinUtil remotely with arguments: [✅] Successful
  - Test 4: Running WinUtil remotely with arguments (as admin): [✅] Successful

## Impact

- Covered by `## Description`, `## Testing / ### Local Tests`, and `## Testing / ### Remote Tests`.

## Issue related to PR

- Resolves #2812

## Checklist

- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Review by og-mrk — CHANGES_REQUESTED** [review]
Although these changes are great, and I do see the effort you've put into this PR.. but downloading WinUtil into Temp folder is something we prefer not doing, and instead downloading WinUtil into RAM (piping result of IRM into IEX). Or in other words, if we can avoid creating Artifact Files, then we should try to avoid it.

**Comment by Cryostrixx** [comment]
> Although these changes are great, and I do see the effort you've put into this PR.. but downloading WinUtil into Temp folder is something we prefer not doing, and instead downloading WinUtil into RAM (piping result of IRM into IEX). Or in other words, if we can avoid creating Artifact Files, then we should try to avoid it.

Hello, @og-mrk! Thanks for the feedback! I understand the desire to run WinUtil in memory instead of creating local files. However, as it stands right now, the process doesn't work correctly, especially when the script tries to relaunch as administrator. Here's an example of the issue:
image

I haven’t yet attempted to implement the in-memory solution, but based on how things function currently, it looks like running from memory might not work as expected without causing issues. I’ll look into it further, but if I can't get it working, the preferred method will likely be to continue using local files.

**Comment by Cryostrixx** [comment]
Hello, @og-mrk!

I appreciate your feedback on my PR, but I want to clarify that I’ve worked hard to ensure the script functions correctly. The current version successfully addresses the issues numerous users have faced and meets the intended goals, which is why I’m confused about the desire for in-memory execution.

I’m open to constructive criticism that can help improve the script, but I hope we can focus on solutions that enhance functionality rather than reverting to behavior that resulted in a non-functioning script.

I'd also like to mention that when you use `Start-Process` the `-WorkingDirectory` parameter is passed by default, preventing issues like this from happening and ensuring the script works as intended:
Screenshot_1

Thanks for your understanding, and I look forward to your feedback!

**Comment by ruxunderscore** [comment]
> Using in-memory execution has caused nothing but problems in the past, as illustrated in the screenshot I shared above.

What issues have there been with executing from in-memory? At the end of the argument, keep in mind that we chose to keep this running in this way to keep from having to store artifacts, as @og-mrk has mentioned, and it's up to Chris whether or not this is changed.

**Comment by Cryostrixx** [comment]
> > Using in-memory execution has caused nothing but problems in the past, as illustrated in the screenshot I shared above.
> 
> What issues have there been with executing from in-memory? At the end of the argument, keep in mind that we chose to keep this running in this way to keep from having to store artifacts, as @og-mrk has mentioned, and it's up to Chris whether or not this is changed.

I understand your point about not wanting to use temporary files but is that really preferable to having the script being non-functional, as shown below?
image

With my fix in place, it works as it was intended to, which you can see in the below screenshot:
image

**Comment by ruxunderscore** [comment]
This is a launch error with Windows Terminal, not the fact that it's run in Ram. I am looking into a fix, now.

**Comment by Cryostrixx** [comment]
@ruxunderscore So what should I do with the PR? I don't want to just close it, as I spent a whole week just ensuring the fix works.

**Comment by ruxunderscore** [comment]
> @ruxunderscore So what should I do with the PR? I don't want to close it yet, as I spent one week just ensuring the fix works.

Keeping it as a draft should be fine. Once I figure out how generate my own winutil.ps1 within my own fork, I can do more testing.

**Comment by Cryostrixx** [comment]
> > @ruxunderscore So what should I do with the PR? I don't want to close it yet, as I spent one week just ensuring the fix works.
> 
> Keeping it as a draft should be fine. Once I figure out how generate my own winutil.ps1 within my own fork, I can do more testing.

You should be able to run these commands to do it, it's the same commands I use to pull in changes from my fork:
```powershell
sl C:\path\to\your\winutil\fork
git checkout your-feature-branch-name
.\Compile.ps1 -SkipPreprocessing
.\winutil.ps1
```
Here's a screenshot showing these commands in effect:
image

-----

Just make sure to replace `C:\path\to\your\winutil\fork` with the full path to your fork, replace `your-feature-branch-name` with the name of the feature branch that contains your changes, and ensure that you pushed your changes to your fork with `git push origin your-feature-branch-name` (you can check this with `git reflog`).

**Comment by ruxunderscore** [comment]
> You should be able to run these commands to do it, it's the same commands I use to pull in the changes from my fork:

I ended doing a partial rollback of changes in an older PR, as I recalled that elevation was working. Only did changes for start.ps1, for now, but may take a look at windev.ps1 later to try to do a partial rollback there as well. Checkout my PR #2913, and let me know if self-elevation works for you, now.

**Comment by Cryostrixx** [comment]
I'm just curious: What even broke? I've been using WinUtil for a while and there was a time when this worked without any issue.
I'll test it now and see if it works.

**Comment by ruxunderscore** [comment]
> I'm just curious: What even broke? I've been using WinUtil for a while and there was a time when this worked without any issue. I'll test it now and let you know how it goes.

After comparing the changes, the only thing I can think of is the handling of arguments.

**Comment by Cryostrixx** [comment]
@ruxunderscore It ran perfectly when testing it locally. No errors there, but there are still issues trying to run it using `irm | iex`:
image

**Comment by ruxunderscore** [comment]
Interesting. I was hosting my ps1 script on another system I have running a webserver and didn't see that issue after my changes. Is this after a compile? And did you remove the old winutil.ps1 if it was still there?

**Comment by Cryostrixx** [comment]
@ruxunderscore See the latest update. I forgot to check out the branch, I'll test it again and let you know how it goes.

**Comment by ruxunderscore** [comment]
> @ruxunderscore See the latest update. I forgot to check out the branch, I'll test it again and let you know how it goes.
> Update: I just tested it, it launches fine but my configuration doesn't seem to be getting imported when I pass `-Config ~\Documents\Configs\winutil.json`.

I believe that was the original intent on the handling of Arguments the way they were, but at this point it's either it runs or doesn't. We can work on a solution for the arguments later.

**Comment by Cryostrixx** [comment]
@ruxunderscore I pushed a fix for the arguments, it's available here: `https://github.com/Cryostrixx/winutil/tree/fix-winutil-admin-elevation-test`.
Please try it out and let me know if it works.

**Pull request closed without merging**
