### PR TITLE
Add's task view tweak

### PR DESCRIPTION
**Pull request by Real-MullaC**
Nothing has changed from edge removal on PR #2136

### CODE REVIEW

**Comment by Real-MullaC** [comment]
@og-mrk How do I remove a file from this PR?

**Comment by og-mrk** [comment]
> @og-mrk How do I remove a file from this PR?

@Real-MullaC I'm sorry, but I haven't understood your question, are you trying to add a new file  using git (telling git to start tracking said new file)?

If so, then you can do so by explicitly telling git to track it, by running something like `git add .\path\to\the\new\file`, or if you know what you've changed (you can check by running `git status`).. then you can run `git add -A` to track all Files, ones that are already tracked, and newly created file(s) that haven't been tracked yet.

**Comment by Real-MullaC** [comment]
> > @og-mrk How do I remove a file from this PR?
> 
> @Real-MullaC I'm sorry, but I haven't understood your question, are you trying to add a new file using git (telling git to start tracking said new file)?
> 
> If so, then you can do so by explicitly telling git to track it, by running something like `git add .\path\to\the\new\file`, or if you know what you've changed (you can check by running `git status`).. then you can run `git add -A` to track all Files, ones that are already tracked by git, and any newly created file(s) that git hasn't tracked yet.

For some reason it added the edge fix to this PR even though I did not add it here and is the same as the other PR I did.

**Comment by og-mrk** [comment]
> > > @og-mrk How do I remove a file from this PR?
> > 
> > 
> > @Real-MullaC I'm sorry, but I haven't understood your question, are you trying to add a new file using git (telling git to start tracking said new file)?
> > If so, then you can do so by explicitly telling git to track it, by running something like `git add .\path\to\the\new\file`, or if you know what you've changed (you can check by running `git status`).. then you can run `git add -A` to track all Files, ones that are already tracked by git, and any newly created file(s) that git hasn't tracked yet.
> 
> For some reason it added the edge fix to this PR even though I did not add it here and is the same as the other PR I did.

Look into the explanation provided in the screenshot below...

image

**Pull request closed without merging**
