### PR TITLE
Remove copied entries in applications.json

### PR DESCRIPTION
**Pull request by Githubguy132010**
I removed a copy of `ditto` and added `ShareX`

This makes winutil less cluttered and nicer to code in.

ShareX is a: Screen capture, file sharing and productivity tool.

Hope you like the PR!
[applications.json](https://github.com/user-attachments/files/15929505/applications.json)

### CODE REVIEW

**Review by og-mrk — CHANGES_REQUESTED** [review]
May I ask what's purpose this newly created file? @Githubguy132010

Also, I noticed that you've added an attachment to the PR (Pull Request) description, hoping that the project maintainer accepts it.. but unfortunately we can't accept your changes that you've made to that attached `applications.json` file, because we do our work using Git, which makes tracking changes (modifying, creating, and deleting files), as well as collaborating with other devs around the world, much much more easier.

I do see that your intention are good.. but please understand that we can't simply upload our files, and let the Project Maintainer figure out what you've changed (in a +2500 lines of code file), and after knowing what has changed (may take some time).. then see if the changes are good enough to be included in the project's code base (again, we're using Git to manage this Chaos.. we're not using FTP Servers & Sys. Admins now adays)

I'm afraid that I must request changes to be made to this PR, as the project maintainer will simply reject your PR & close it.

**Comment by RocGod** [comment]
@og-mrk I totally agree your point... I didn't get what @Githubguy132010 is trying to do...

**Comment by Githubguy132010** [comment]
Look, I'm new to Github so I dont really now how it works. So I really appericiate this feedback.
The purpose of this file is to remove copied application entries in winutil.

I simply asked ChatGPT how to create a PR on Github because I dont know anything about Git.

I just thought that it was fun to contribute and this came out of it.

So if I need to change anything, just tell me what to change.

**Comment by RocGod** [comment]
@Githubguy132010 If you don't know how Git works, please google or check some Youtube videos and learn it... 
This PR makes no sense at all, need to be closed.  @og-mrk

**Comment by Githubguy132010** [comment]
I will close it.

**Pull request closed without merging**
