### PR TITLE
Add 'Figma' App into 'applications.json' File

### PR DESCRIPTION
**Pull request by og-mrk**
### Issues this PR tries to resolve

Resolves: https://github.com/ChrisTitusTech/winutil/issues/2073

### CODE REVIEW

**Comment by KonTy** [comment]
@og-mrk Figma is not FOSS and on top of that it is Adobe. Adobe is everything that is opposite of FOSS. Did you see thier latest change to the terms of service? My suggestion please check is the tool we are adding is FOSS and if in doubt reject it. :)

**Review by ChrisTitusTech — CHANGES_REQUESTED** [review]
How about we switch this to PenPot and specify it as a Figma Alternative.

**Comment by og-mrk** [comment]
> How about we switch this to PenPot and specify it as a Figma Alternative.

After a bit of searching online, it looks like PenPot is a Web-Based Application, no Desktop edition available for Windows (or any other main stream OS), and so no WinGet or Choco package to find, therefore I can't replace Figma with PenPot in this PR.

If this addition is not accepted for one or more reasons, like the ones highlighted by @KonTy 's [Comment](https://github.com/ChrisTitusTech/winutil/pull/2074#issuecomment-2166739606), I have no problems closing this PR with respect to both you, Chris, and to the people agreeing with the Ideas of FOSS.

**Comment by KonTy** [comment]
Yeah PenPot can be ran from a docker container, which makes setup pretty complicated we at my company are switching to Lunacy since, it is free and can load Figma files directly. But we still do worry that at some point Lunacy might decide to go paid and screw users. :)

**Comment by SHR1SHAK** [comment]
> @og-mrk Figma is not FOSS and on top of that it is Adobe. Adobe is everything that is opposite of FOSS. Did you see thier latest change to the terms of service? My suggestion please check is the tool we are adding is FOSS and if in doubt reject it. :)

To my knowledge figma and Adobe parted ways.

**Pull request closed without merging**
