### PR TITLE
Remove trailing whitespace characters

### PR DESCRIPTION
**Pull request by og-mrk**
### How to achieve what this PR has done (For Educational/Informative Purposes)

This is made possible through the follow commands (all done inside Git Bash, to utilize Powerfull Unix-Based CLI Tools):
1. Find every File `*.*`, then remove all whitespace characters and pipe it into a temporary file, and copy that temporary file's contents into its original file:
```sh
find . -type f -name "*.*" -exec sh -c 'for i;do sed 's/[[:space:]]*$//' "$i">/tmp/.$$ && cat /tmp/.$$ > "$i";done' arg0 {} +
```

2. Find every File `*.*` _again_, this time change it's New Line Character to be `CRLF` (DOS Style) instead of `LF` (Unix Style):
```sh
find . -type f -name "*.*" -exec sh -c 'for i;do unix2dos.exe "$i";done' arg0 {} +
```

3. Restore some files that don't make sense to "Remove Trailing Whitespace Characters".. because some are Binary Files, some are file that shouldn't be changes (auto-generated files), like `winutil.ps1` compiled script, as well as ~O&O Shutup Config Files~ _support for these config files dropped in a recent PR_:
```sh
git restore winutil.ps1 releases/oscdimg.exe screen-install.png wiki/Get-Installed.png wiki/Settings-Export.png
```

4. Look at the final result inside the terminal (or through a Git GUI Client):
```sh
git diff --word-diff-regex="[ ]+|[^ ]+"
```

### References

- Tried doing it manually by viewing the `git log --check` output, and trying to figure out (somehow, though pattern matching tools) which part is where in the project.. yahh this idea didn't last for long 😅 This was done through Vim (NeoVim).
  [link to StackExchange Question I found](https://vi.stackexchange.com/questions/454/whats-the-simplest-way-to-strip-trailing-whitespace-from-all-lines-in-a-file)
- The multi-part, one line command I used to find every file recursively, and do some operation on it (in this case, removing Trailing WhiteSpace Characters).
  [Link to the StackOverFlow Question](https://stackoverflow.com/questions/10711051/how-to-remove-trailing-whitespaces-for-multiple-files)
- View the Git Diff of Only WhiteSpace Characters Changes (Addition or Deletion).
  [Link to the StackOverFlow Question](https://stackoverflow.com/questions/52123651/how-to-show-whitespace-differences-with-git-word-diff)

### CODE REVIEW

**Comment by og-mrk** [comment]
@ChrisTitusTech
This PR might result in Merge Conflicts, in that case please make sure that you merge it last, so I could resolve any conflicts that may occur 👍

And this particular PR is considered of lower priority as well, as it doesn't add new functionality/bug fixes to the project, but it does make things a bit nicer IMHO.

**Comment by og-mrk** [comment]
@ChrisTitusTech PR is ready for review (fix merge conflicts in commit https://github.com/ChrisTitusTech/winutil/pull/2149/commits/19ed50b449b0b9fe0433409bd37331c71413cf24)

**Review by ChrisTitusTech — APPROVED** [review]

**Comment by ChrisTitusTech** [comment]
Can't merge. Conflicts exist.

**Comment by og-mrk** [comment]
> Can't merge. Conflicts exist. 

One moment, starting my laptop...

**Comment by ChrisTitusTech** [comment]
One more time... These cleanups are a pain to merge and most times I just deny them.

**Comment by og-mrk** [comment]
> One more time... These cleanups are a pain to merge and most times I just deny them.

Fixed merged conflicts.. _for the second/third time 💀_
commit https://github.com/ChrisTitusTech/winutil/pull/2149/commits/0da09c04c07371e53bfc9b677996fbc810039661

\+ I do agree that merge conflicts can be a pain at times.. but nothing can't beat patience & strong will 💪

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
