### PR TITLE
Added Betterbird application to "Communications"

### PR DESCRIPTION
**Pull request by Today20092**
Betterbird is a better version of thunderbird email client.

### CODE REVIEW

**Comment by blusewill** [comment]
Better switch this to the draft.
Project is currently on refracting. All of the Apps Request will be canceled

**Comment by Today20092** [comment]
@blusewill where is the draft? i am only seeing two branches, `main` and `test-2024-02-07-refactor-noapps`

**Comment by blusewill** [comment]
No. I mean recommend set the Pull Request to Draft.
But close it is also fine and after the refactor project is done you can request it again

**Comment by Today20092** [comment]
@blusewill thank you for that!

**Pull request closed without merging**
