### PR TITLE
Updated DNS box  Hotfix

### PR DESCRIPTION
**Pull request by Joanty24**
I forgot to update the DNS GUI box in my last merged pull request. It was in the original one but not in the merged one.

### CODE REVIEW

**Review by Real-MullaC — APPROVED** [review]

**Review by ChrisTitusTech — APPROVED** [review]

**Comment by ChrisTitusTech** [comment]
@Joanty24 Curious why level 3 removed? 4.2.2.2 is still a pretty dominate dns server.

**Comment by Joanty24** [comment]
> @Joanty24 Curious why level 3 removed? 4.2.2.2 is still a pretty dominate dns server.

I could not find its IPv6 address. I'm planning to put it back (indicating that it only does IPv4).

**Comment by ChrisTitusTech** [comment]
Very interesting, I just checked as well and you are indeed correct @Joanty24 Level3 doesn't have ipv6 servers. I approve the PR and we can remove them.

**Review by ChrisTitusTech — APPROVED** [review]

**Comment by Joanty24** [comment]
I think it's ready to merge @ChrisTitusTech .

**Review by og-mrk — APPROVED** [review]
The changes looks good, thanks @Joanty24 😄

### Screenshot(s)
image

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
