### PR TITLE
Added Cursor AI code editor

### PR DESCRIPTION
**Pull request by SHR1SHAK**
Cursor is an AI-first code Editor that transcends traditional Integrated Development Environments (IDEs) by integrating artificial intelligence to enhance the coding experience significantly.

### CODE REVIEW

**Comment by MyDrift-user** [comment]
Hey @SHR1SHAK 

As seen in #2234, the package does not work when trying to install. Have you tested if that is still the case?

**Comment by SHR1SHAK** [comment]
I have tested using this argument <code> winget.exe install --id Anysphere.Cursor --exact --source winget --accept-source-agreements --version "0.37.1" --silent --disable-interactivity  --accept-package-agreements </code> do i also need to inside the whole thing to work ?

**Comment by og-mrk** [comment]
> I have tested using this argument ` winget.exe install --id Anysphere.Cursor --exact --source winget --accept-source-agreements --version "0.37.1" --silent --disable-interactivity --accept-package-agreements ` do i also need to inside the whole thing to work ?

@SHR1SHAK 
The `--version "0.37.1"` part isn't necessary, as it's the latest version for `Anysphere.Cursor` WinGet Package.
Also as far as I know, the `--disable-interactivity` flag isn't used by WinGet Package Install/Uninstall Function, so is this flag required to make this package install/uninstall successfully? Thanks in advance.

**Review by og-mrk — APPROVED** [review]
If the WinGet Package `Anysphere.Cursor` work as excepted.. then the rest of the PR changes look good to me.

### Screenshot
image

**Comment by SHR1SHAK** [comment]
For this PR I have just added the ID for Winget "Anysphere.Cursor" but it error out. To install successfully using winget <code>Anysphere.Cursor --exact --source winget --accept-source-agreements --version "0.37.1" --silent --disable-interactivity --accept-package-agreements</code> this whole thing should be used. My question is can winutil use the whole argument in json file? @og-mrk

**Comment by og-mrk** [comment]
> For this PR I have just added the ID for Winget "Anysphere.Cursor" but it error out. To install successfully using winget `Anysphere.Cursor --exact --source winget --accept-source-agreements --silent --disable-interactivity --accept-package-agreements` this whole thing should be used. My question is can winutil use the whole argument in json file? @og-mrk

If you see the screenshot posted in [this comment](https://github.com/ChrisTitusTech/winutil/pull/2445#issuecomment-2248495521) you'll find what arguments are passed to WinGet whenever you install any program that has a WinGet ID (_almost_ all apps in `applications.json` File has a WinGet ID), and for providing arguments inside the json file, although it's a nice idea.. I don't recommend doing this, as it'll introduce more bugs, and increase maintenance time on Install/Uninstall Logic, plus it'll bloat the `applications.json` File even more (which FYI.. it's copy-pasted into the compiled `winutil.ps1` file when you run `Compile.ps1` Script, which's something to consider long-term with File Size).

All things considered.. I would (as a suggestion to you, or "If I was in your shoes" kind of thing) make this PR as Draft, and make another PR changing the `Install-WinUtilProgramWinget` Private Function to handle such case (maybe try adding that `--disable-interactivity` flag?).

**Comment by SHR1SHAK** [comment]
Yeah, I think I'm setting this PR to draft for now. But with all my testing the argument is required for successful installation.

**Pull request closed without merging**
