### PR TITLE
Fix IPv6 DNS | Hotfix

### PR DESCRIPTION
**Pull request by Joanty24**
I forgot to update the DNS GUI box in my last pull request. It was in the original one but not in the merged one.

### CODE REVIEW

**Review by Real-MullaC — CHANGES_REQUESTED** [review]
image
What are the DNS records for these?

Also please remove the winutil.ps1 file.

**Comment by Joanty24** [comment]
It auto compiles the winutil.ps1. I removed it now.

Those DNS records where added with my last pull request. In the original one I also updated the GUI but forgot doing it in the merged one, so fixing it now.

**Comment by Real-MullaC** [comment]
> It auto compiles the winutil.ps1. I removed it now.
> 
> Those DNS records where added with my last pull request. In the original one I also updated the GUI but forgot doing it in the merged one, so fixing it now.

It is still there.

**Comment by Joanty24** [comment]
> > It auto compiles the winutil.ps1. I removed it now.
> > Those DNS records where added with my last pull request. In the original one I also updated the GUI but forgot doing it in the merged one, so fixing it now.
> 
> It is still there.

Seeing it now, how can I disable the auto compile?

**Comment by Joanty24** [comment]
I will open a new pull request from a branch it hope it won't auto compile.

**Comment by og-mrk** [comment]
Hello @Joanty24
to avoid this Auto Compile issue, and to make future contributes easier (on your side), it's better to Branch off main branch (on your fork) and make your changes in the new git branch, then make a PR.

If you have any question, you can send them here or by using our new [Un-Official Community Discord Server](https://discord.com/invite/RUbZUZyByQ)

**Pull request closed without merging**
