### PR TITLE
OO Shutup 10 Tweaks revamped

### PR DESCRIPTION
**Pull request by Marterich**
**!!! IMPORTANT !!! Because the PR relies on downloading files directly from the Git Repo (Main), any tests will fail until the config files are moved there or the download links in "Invoke-WPFOOSU" are modified for testing**
- Created a config file that contains the recommended changes by the newest version of OO Shutup 10
- Created a config file that contains the factory settings
- Changed the location of the config files to reside in the config directory
- Added functionality to undo the tweaks by OO Shutup
- Added a button in the Advanced  Tweaks section to open the OO Shutup GUI to modify the settings manually #1812 
- Moved all of the logic for downloading and applying the tweaks from the tweaks.json to a public function "Invoke-WPFOOSU"
- Added -Wait to the execution parameters to avoid race condition when run together with temp file removal (Should fix: #1822 )

The motivation for this PR was, that I kept reading issues #1813 from people who eg. couldn't enable location services anymore after running the toolbox. Further digging resulted in a few realizations:
1. The old config file disabled location services completely via policies
2. No functionality was built into the script to reset or modify the behavior of OO Shutup 10 
3. The old configuration file was created using an older version of OOSU so not all new and shiny options were present inside.

Furthermore, I decided, that because OOSU and the config file are kind of a black box to most users, it would probably be best to rely on the default, unaltered recommendations by oo-software that do not break the functionality of apps (like disabling location services completely) and rather provide a simple way of starting the program directly if a user should decide that they want to apply some of the more intrusive optimizations.

### CODE REVIEW

**Comment by ChrisTitusTech** [comment]
I like the changes, but at this point we probably should remove O&O from the utility as most of the changes it makes are already in the tweaks itself. Downloading the exe and config seems too cumbersome.

**Comment by ChrisTitusTech** [comment]
> > I like the changes, but at this point we probably should remove O&O from the utility as most of the changes it makes are already in the tweaks itself. Downloading the exe and config seems too cumbersome.
> 
> Allow me to doubt that statement. When you say "most of the changes is makes" it implies you went through each and every setting it has both for local machine and current user recommended settings, which takes up a lot of time and effort and dedication. But that's not enough, let's say you did went through each and every setting - who said your commands cover O&O commands one-to-one? Example of what I mean by that - O&O would disable Bing search by 2 commands, one for local machine and one for current user, now how do you know what O&O did on the background in terms of which were the right commands to disable Bing search in terms of which reg files it modified? Also you have to take into consideration that O&O updates one in a while and could change it commands and/or features, someone has to keep an eye out for updates and implement them into winutil.
> 
> Look, all I'm saying is if you want to remove O&O that's fine, but make sure to implement 100 percent of it and not 60 percent and do it accurately in terms of which reg files to modify and commands to use, and most importantly - check for O&O updates and implement any new setting.

I am sure I missed something in the O&O Tweaks that they do cover. The main thought is running this on top of the tweaks is a bit overkill and I am more worried about O&O changing the recommended to something I disagree with. It hasn't happened in the past couple of years, but being less dependent on them would be an overall net win even if a few tweaks O&O makes are missed.

**Comment by Marterich** [comment]
It could also be an option to remove the OO Tweak with the preconfigured config from the simple tweaks, but keep the Button in the advanced section that just simply starts the Tool. This way, it would not be neccessary to maintain the OO config files, and keep them up to date, but it would still allow the end user to start the application by the simple click of a button instead of needing to download and run the tool manually.

**Comment by ChrisTitusTech** [comment]
Thanks for humoring me, I love all those suggestions. On the next update I'm going to pick these out and get it implemented. I will leave this PR open for now until I get ready to merge to main.

**Pull request merged**
