### PR TITLE
[01] Refactoring UI code

### PR DESCRIPTION
**Pull request by og-mrk**
### Some Background

This PR is the first of a series of PRs on updating the UI of WinUtil. This can be considered a response to the Progress Tracking Issue Ticket #2226 

> [!NOTE]
> This PR is a big one, and I don't know if it'll be accepted or not.. but here goes nothing 🤷.
> Also, I've left `Allow edits and access to secrets to maintainers` checked on, meaning @ChrisTitusTech can change the files in the PR and push them in a new commit onto my own branch (The git branch this PR is based on).

### Showcase of the changes

code_refactoring_01_showcase2

### Highlights

- Re-Wrote the `Get-TabXaml` Private Function so it can be more maintainable, Updated its Docs, and made the Generated XML Code be more readable using Tabs. ( commits acd4d7121e26251d47842f0d05ae0437bb074aed , d897b1dfc81d5292ba8bc48660dc3cdd2895cbc9 , 640d28ac109521a836cefa32689e3302de86a601 , 892f59a15418bf32e2400ec000b527ad842602b2 , ebfdaafde72b25a1ec503a172b7e17445773a3b2 )
- Re-order some tweaks & Update their Content Fields to be more descriptive. ( commit 827bb592cbdc83d764e4130cbb20cfecbe82a8f9 )
- Add a lot more Theming Options so that Contributors have an easier time changing the looks of WinUtil _without_ the need to edit the XML File. ( commits 640d28ac109521a836cefa32689e3302de86a601 ,  3254314ba979c33735e22bdfb2680aab9018e0f8 , 2342f81a06fdbdd6d80605e2dbb714e90d237381 , 18f9ea504248b12abac3b12fefaa561adae714d0 )
- Make the Toggle Buttons be on the Left-side rather than the right side, and remove the hard to deal with (from a UI maintaining prospective) the `On` & `Off` Text next to the Toggle. ( commits 74cf8f0808a96eb34d58b0c0a6994c4ead70e32e , 3d3748da24e7cc7b0100582c6e5df902d7ce8602 )
- Extend `Show-CustomDialog` Function to have more options/parameters. ( commit 3254314ba979c33735e22bdfb2680aab9018e0f8 )
- [TEMPORARY FIX] Add optional 'ButtonWidth' Field to Config Json Files that use 'Button' Type. ( commit 47413195914d06f445a80ce2c3db02d82cd18c9c )
  meaning no more un-clear `"Type": "SOME-VALUE-HERE"` kind of way of handling Button Widths.. but I still don't know if this's the best approach to solving this problem.

### Additional Info

The font size for everything, the Margins for checkboxes, the font family, and more.. all of these can be changed through the `themes.json` file, so if you don't like how WinUtil looks in this PR changes.. then it's relatively easy to change.
1. edit the `theme.json` File.
2. (Re-)Compile WinUtil.
3. Run `winutil.ps1` as Admin & see your changes.

> [!NOTE]
> Currently WinUtil doesn't use any Math Solver library, meaning I can't make the values of attributes in other elements _**be based of**_ a value used elsewhere, plus do some math on it (Addition & Subtraction works.. _most of the time_, Multiplication & Division is outright, not supported in WPF attributes).
> So.. things like MicroWin Checkboxs having _Custom Margins_, as _I've changed_ the Checkbox Margins in `themes.json` file. ( commit 2342f81a06fdbdd6d80605e2dbb714e90d237381 )
> A negative value for the margins is used.. because we want these Checkbox in MicroWin Tab to push it to the left side, makes a bit of sense if you did HTML & CSS before).

### CODE REVIEW

**Comment by SHR1SHAK** [comment]
The toggle on the left looks so nice and clean and also solves the problem of negative space while it was on the right. 👍

**Review by MyDrift-user — CHANGES_REQUESTED** [review]
Nice work @og-mrk!

I generally like the changed you've made and how you implemented most of them.

### Change Request

I suggested another way of implementing the buttonwidth into the json since you're not sure if that is the way to go. I personally find it better in terms of maintainability and more compact, but a bit less easy to understand for new contributers so idk..

---

I like the Preference Toggles, I once also changed the positioning of the toggle like that but it was overwritten by another PR that redesigned it, Thanks :)

---

Making the UI elements smaller in general is a good Idea thinking about how much the Toolbox has grown.

**Review by Real-MullaC — APPROVED** [review]

**Review by ChrisTitusTech — APPROVED** [review]
Big Changes, but I love a lot of these tweaks as it as a lot of polish to the GUI and maintainability. I'm going to test this some more, but overall I approve.

**Comment by Real-MullaC** [comment]
@og-mrk Please dm me ASAP

**Pull request merged**
