### PR TITLE
add verbose logon

### PR DESCRIPTION
**Pull request by padsalatushal**
Enable or disable verbose sign in status messages. Verbose status messages may be helpful when you are troubleshooting slow startup, shutdown, logon, or logoff behavior.

### CODE REVIEW

**Comment by padsalatushal** [comment]
Source : https://learn.microsoft.com/en-us/troubleshoot/windows-server/performance/enable-verbose-startup-shutdown-logon-logoff-status-messages

**Comment by DeveloperDurp** [comment]
@padsalatushal We can compress this into one checkbox, especially if it's that one registry value. With the undo function users would be able to enable and disable this without the need of 2 checkboxes

**Comment by padsalatushal** [comment]
@DeveloperDurp thanks for the suggestion. I will make changes.

**Comment by padsalatushal** [comment]
can we do same with disable power throttling and disable mouse acceleration feature.?

**Comment by DeveloperDurp** [comment]
Yes, those can be converted to a single checkbox as well

**Comment by padsalatushal** [comment]
one more question :  
is it a good idea to turn the checkbox button to a toggle button like 
image

**Comment by DeveloperDurp** [comment]
We could, however dark mode is a little special. It has logic that when it's "checked" or "unchecked" it will execute a function. There is also a function to get the state when winutil starts. I have ideas about handling this but because that is also a checkbox you can't make a blanket function like I do for every button, otherwise every checkbox would start executing code every time you check or uncheck a box.

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
