### PR TITLE
Install flow rework

### PR DESCRIPTION
**Pull request by ty802**
Separated Winget and Chocolatey setps when installing software add skip them when not needed

### CODE REVIEW

**Review by ChrisTitusTech — COMMENTED** [review]
Oh this looks far better than my garbage code I put in yesterday. Can't wait to give it a try.

**Comment by ty802** [comment]
It still needs a bit of work with the uninstall
I didn't implement uninstalling with Chocolatey
but that's a pretty simple fix and it wasn't implemented in the first place so there shouldn't be any lost functionality

**Comment by og-mrk** [comment]
@ty802 Thanks for these great changes of yours.
Just wanna inform you that I've implemented the Uninstall Command for choco in a new PR to your WinUtil Fork (here's [a link](https://github.com/ty802/winutil/pull/1) to it), as well as a simple feature (Automatic Upgrade).

Thanks again for these patches/fixes, and have a nice day 😄

**Comment by ChrisTitusTech** [comment]
@og-mrk going to pull this in, might just have you resubmit the pr on the test branch when you get a chance.

**Comment by og-mrk** [comment]
> @og-mrk going to pull this in, might just have you resubmit the pr on the test branch when you get a chance.

@ChrisTitusTech Kind of buzzy these days, will try as soon as I can + complete the implementation (need more polishing/testing), if I don't do so in the next week (until "due day/deadline", which's 5/20), then anyone can re-commit my commits in a PR, as well as add any necessary changes to make it fully functional.

hope you can understand, and have a nice day Chris 😄

**Pull request merged**
