### PR TITLE
add undoscript feature + implement it on every tweaks

### PR DESCRIPTION
**Pull request by padsalatushal**
added undoscript feature

### CODE REVIEW

**Comment by padsalatushal** [comment]
@DeveloperDurp  thanks for the great explanation and always helping. 
can you check this ?

**Comment by padsalatushal** [comment]
@DeveloperDurp 
list of tweaks that have an InvokeScript. I will add undo script for these tweaks.
  - WPFEssTweaksTele
  - WPFMiscTweaksDisplay
  - WPFEssTweaksDeBloat
  - WPFEssTweaksStorage
  - WPFEssTweaksRemoveEdge
  - WPFMiscTweaksRightClickMenu (already done in this pr )
  - WPFEssTweaksRemoveCortana

**Comment by padsalatushal** [comment]
#3

**Comment by padsalatushal** [comment]
WPFEssTweaksTele and WPFEssTweaksDeBloat are remaining for undo script .

**Comment by padsalatushal** [comment]
@ChrisTitusTech this pr is good to merge. WPFEssTweaksTele and WPFEssTweaksDeBloat are both remaining for undo script I will make another pr for that after doing some testing.

**Comment by DeveloperDurp** [comment]
Can you cleanup Invoke-WinUtilTweaks.ps1it still has the 2 if statements for InvokeScript and UndoScript and is in the wrong spot in the script.

**Comment by dreamsyntax** [comment]
Felt this is relevant, undo does not work for the "run OOShutup" option. Search breaks for local installations with winutil.
The interesting part is its inconsistent. I've done a few tests on clean windows 10 installs and most of the time it breaks. Sometimes it does not.

See #569

**Comment by padsalatushal** [comment]
> Can you cleanup Invoke-WinUtilTweaks.ps1it still has the 2 if statements for InvokeScript and UndoScript and is in the wrong spot in the script.

can you explain how to implement that? because I tested previous code you share and it didn't work

**Comment by DeveloperDurp** [comment]
Try

```powershell
function Invoke-WinUtilTweaks {
    <#
    
        .DESCRIPTION
        This function converts all the values from the tweaks.json and routes them to the appropriate function
    
    #>

    param(
        $CheckBox,
        $undo = $false
    )
    if($undo){
        $Values = @{
            Registry = "OriginalValue"
            ScheduledTask = "OriginalState"
            Service = "OriginalType"
            ScriptType = "InvokeScript"
        }

    }    
    Else{
        $Values = @{
            Registry = "Value"
            ScheduledTask = "State"
            Service = "StartupType"
            ScriptType = "UndoScript"
        }
    }
    if($sync.configs.tweaks.$CheckBox.ScheduledTask){
        $sync.configs.tweaks.$CheckBox.ScheduledTask | ForEach-Object {
            Set-WinUtilScheduledTask -Name $psitem.Name -State $psitem.$($values.ScheduledTask)
        }
    }
    if($sync.configs.tweaks.$CheckBox.service){
        $sync.configs.tweaks.$CheckBox.service | ForEach-Object {
            Set-WinUtilService -Name $psitem.Name -StartupType $psitem.$($values.Service)
        }
    }
    if($sync.configs.tweaks.$CheckBox.registry){
        $sync.configs.tweaks.$CheckBox.registry | ForEach-Object {
            Set-WinUtilRegistry -Name $psitem.Name -Path $psitem.Path -Type $psitem.Type -Value $psitem.$($values.registry)
        }
    }
    if($sync.configs.tweaks.$CheckBox.$($values.ScriptType)){
        $sync.configs.tweaks.$CheckBox.$($values.ScriptType) | ForEach-Object {
            $Scriptblock = [scriptblock]::Create($psitem)
            Invoke-WinUtilScript -ScriptBlock $scriptblock -Name $CheckBox
        }
    }

    if(!$undo){
        if($sync.configs.tweaks.$CheckBox.appx){
            $sync.configs.tweaks.$CheckBox.appx | ForEach-Object {
                Remove-WinUtilAPPX -Name $psitem
            }
        }

    }
}
```

**Comment by padsalatushal** [comment]
image
 for me it still not work give lots of error like this

**Comment by DeveloperDurp** [comment]
That means one of your config files is broken

**Comment by padsalatushal** [comment]
yeah now it works thanks

**Comment by padsalatushal** [comment]
@ChrisTitusTech  Good to merge.

**Comment by padsalatushal** [comment]
@ChrisTitusTech good to merge.

**Comment by ChrisTitusTech** [comment]
Awesome, Thanks for all the hard work @padsalatushal

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
