### PR TITLE
tweaks and fetures tabs clean up automation from inputXML.xaml

### PR DESCRIPTION
**Pull request by ogfrm**
- remove tweaks and feature items from inputXML.xaml file
- add context and descriptions to tweaks.json and feature.json files
- add type to items like button, toggle, combobox  to automate add to inputXML.xaml file
- change the main.ps1 file to add not just application items but also tweaks and features to inputXML.xaml file
- in application.json WPFInstallOPAutoClicker has a panel as 5, that is why the original version does not show it
  my version will create 6th column just for that if you change it to 4 application tab will be reduced to 5 column

### CODE REVIEW

**Comment by KonTy** [comment]
I'm getting this error when I load winutil from your fork

``` Powershell
convertfrom-json : Invalid JSON primitive: .
At line:8058 char:6
+ }' | convertfrom-json
+      ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

convertfrom-json : Invalid JSON primitive: .
At line:10802 char:6                                                                                                    + }' | convertfrom-json                                                                                                 +      ~~~~~~~~~~~~~~~~                                                                                                     + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException                                       + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand             
```

**Comment by KonTy** [comment]
Also did you have a chance test loading times? It loads much slower on my machine then the previous build.

**Comment by ogfrm** [comment]
I do not get any error. I even cloned my pr from https://github.com/ChrisTitusTech/winutil  and still no error. My loading times are ok. But I will close my pr and retest it again. Thanks for testing it.

**Comment by KonTy** [comment]
@ogfrm keep up the good work, appreciate your contributions. Also, if you have the time could you look at incorporating my new code for Install Apps tab please? I just don't have the time to push it forward right now. Basically what it does it splits all the apps evenly betwen 5 columns to better utilize space. Look here for a demo: ``irm https://raw.githubusercontent.com/KonTy/winutil/test-2024-01-15/winutil.ps1 | iex``

and code of interesting is ofcouse in teh main.ps1 when it seems you are familiar with but it is trivial, basically get total number of apps / 5 and as you add them to panels change panel number when you reach total/5 :-). Also doing this way we don't need panel number in the json anymore, since it is automatic

Thank you and keep up the good work, any contribution is very much appreciated.

**Pull request closed without merging**
