### PR TITLE
Fix/Refactor windev Admin Elevation

### LINKED ISSUE #2668: Broken Run as admin (windev)
## Describe the bug
Broken Run as admin (windev)

## To Reproduce
1. Open powershell un-elevated
2. `irm "https://christitus.com/windev" | iex`

## Expected behavior
Obviously should be successful elevating to admin

## Screenshots
image

### PR DESCRIPTION
**Pull request by Marterich**
## Type of Change
- [x] Bug fix
- [x] Refactor

## Description
Changed the auto elevation logic to use the same URLs whether windev is called as admin or not.
(previously a static URL was used when the shell wasn't run as admin) 

## Issue related to PR
- Resolves #2668

### CODE REVIEW

**Comment by MyDrift-user** [comment]
@Marterich it was done because otherwise when launchin the winutil dev release it will elevate and run the latest full release instead of the originally launched dev release. There might be a better fix but that was mine at the time..

**Comment by Marterich** [comment]
> @Marterich it was done because otherwise when launchin the winutil dev release it will elevate and run the latest full release instead of the originally launched dev release. There might be a better fix but that was mine at the time..

Allright, I'll take another look

**Comment by MyDrift-user** [comment]
If you only want to fix the attached issue, you may remove/fix the $arglist bc the rest should work fine

**Comment by Marterich** [comment]
> If you only want to fix the attached issue, you may remove/fix the $arglist bc the rest should work fine

I updated the logic and the PR Description. Now the same URLs are being used, whether /windev is called as a privileged user or not.

**Review by MyDrift-user — APPROVED** [review]
looks good to me, thanks :)

**Comment by MyDrift-user** [comment]
wait, shouldn't you escape `Invoke-RestMethod` under $script = `Invoke-RestMethod $url`?

**Comment by Marterich** [comment]
> wait, shouldn't you escape `Invoke-RestMethod` under $script = `Invoke-RestMethod $url`?

This is not really necessary because Powershell is not as strict as bash for example, meaning, if Invoke-RestMethod is a known module/function it gets directly invoked. Winutil gets downloaded and stored in $script and later passed as a string to iex

**Review by ChrisTitusTech — APPROVED** [review]

**Comment by ChrisTitusTech** [comment]
Fantastic way of elevating it properly. Thanks @Marterich 

I haven't forgotten about the Choco tweak, I just wanted to show that on stream when I merge it.

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
