### PR TITLE
added option to change dns

### PR DESCRIPTION
**Pull request by padsalatushal**
Added a dropdown menu box for choosing DNS like google, cloud flare, level3, and OpenDNS. After selecting when the run tweak button press changes DNS for all connations. The default value is a default that does not change anything.

### CODE REVIEW

**Comment by padsalatushal** [comment]
@DeveloperDurp I am not good at XAML. I want the DNS text and drop-down menu in one line. 
image

**Comment by DeveloperDurp** [comment]
I am not sure either, I haven't used XML for my GUI's before so it's new to me as well.

**Comment by padsalatushal** [comment]
@ChrisTitusTech This PR is merged but I can't see these changes in any branch. Should I have to create a new PR?

**Comment by ChrisTitusTech** [comment]
@padsalatushal Yes, we had a bad PR so I had to wipe out a few of them.

Sorry about that. I'm going to have to vet PRs better to avoid rollbacks like this.

**Pull request merged**
