### PR TITLE
fix shortcut creation

### LINKED ISSUE #2487: "Create WinUtil Shortcut" not working properly with latest release.
## Describe the bug
When trying to create a shortcut for winutil on the latest release it creates the shortcut but when going to open winutil using the shortcut it only opens "This PC" in my File Explorer. When right clicking the shortcut it does not give me any "open with" option either. Shortcuts made before current release has worked flawlessly on 2 of my Windows 11 Systems.

## To Reproduce
1. Go to "Tweaks" tab in winutil.
2. Click on "Create Shortcut"
3. Attempt to open shortcut in saved location.
4. Met with file explorer being opened on the "This PC" tab.

## Expected behavior
When clicking/opening the shortcut I expect Winutil to open like it has done with "older" shortcut versions before.

## Screenshots
Adding screenshots that show steps of issue.

## Additional context
Wanted to make a new shortcut as I had cleaned up my secondary PC and removed the old shortcut without realising. After attempting to make a new shortcut I am met with this issue.
System is Windows 11: Version 23H2 (OS-version 22531.3880)
image
image
image

### LINKED ISSUE #2510: Winutil shortcut broke
## Describe the bug
Myself and my father use WinUtil on a regular basis, and we have found that WinUtil shortcut doesn't re-open the winutil prompt

## To Reproduce
1. Open up WinUtil
2. Click on Tweaks
3. Click on Create winutil shortcut
4. Make the Shortcut
5. Close out of WinUtil
6. Click on the shortcut

## Expected behavior
Should re-open winutil using PWSH or Powershell

## Screenshots

ezgif-1-886e637a20

### LINKED ISSUE #2520: It seems the shortcut created by WinUtil just opens up the This PC section of File Explorer. It doesn't run the actual script.
## Describe the bug
Title.

## To Reproduce
Run the script, click the Create Shortcut button and save the WinUtil shortcut, use the shortcut.

## Expected behavior
The shortcut runs the WinUtil script.

## Screenshots
N/A.

## Additional context
N/A.

### PR DESCRIPTION
**Pull request by MyDrift-user**
# Pull Request

## Type of Change
- [x] Bug fix

## Description
- using vars that actually exist instead of imaginary ones.
- remove empty row at the start of the file

## Testing
tested, did not work before, works now

## Issue related to PR
- Resolves #2487
- Resolves #2510
- Resolves #2520

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Review by Real-MullaC — APPROVED** [review]

**Comment by michaeldun123** [comment]
I've actually just made an issue regarding this :D https://github.com/ChrisTitusTech/winutil/issues/2510

**Review by michaeldun123 — APPROVED** [review]

**Review by og-mrk — APPROVED** [review]
Because GitHub doesn't allow adding review comments on lines that haven't changed by PR, I'll mention it here..

@MyDrift-user If you can/have the time, can you remove [this new line](https://github.com/ChrisTitusTech/winutil/pull/2488/files#diff-c56ff008d37d9b05212be75e4b7a2b429bfb4f3d3b97634a68b9926189ba4ff9R34)?
I know it's something to nit-pick, and it isn't even a concern of this PR.. but if you're modifying same file, might as well point out other "issues" it might have (which again, not really a big deal).

Overall, nice fix to Shortcut Creation 👍

**EDIT**: @MyDrift-user Can you add Issue #2520 to the `Issue related to PR` section?

**Comment by MyDrift-user** [comment]
Hey @og-mrk 
Thanks for the advice, the link does not direct me to an empty line, if you mean the one before the function in the file I have already removed it, if not I do not know which line you mean..

**Review by ChrisTitusTech — APPROVED** [review]
Looks good

**Comment by MagmaBro123** [comment]
Seems this still ocurrs.

**Comment by MyDrift-user** [comment]
> Seems this still ocurrs.

@MagmaBro123 this will be fixed for the following release

**Pull request merged**
