### PR TITLE
Update Winget Install and Uninstall / Add NuGet and Microsoft.Winget.Client Modules

### PR DESCRIPTION
**Pull request by ruxunderscore**
- Changed how WinGet installs and uninstalls are handled, by utilizing `Install-WinGetPackage` and `Uninstall-WinGetPackage`.

I learned today that PS Modules utilizing WinGet are installed alongside WinGet as of a few years ago. With the changes to how Winget Updating is handled by my other PR #1829, this should be a better solution to handling installs going forward. In the cases I tested, checking Status was the best way to handle issues with a package installer not having machine scope capabilities. 

If anyone has any better ways to handle this, let me know. 

This should fix issues, like: #1805 #1756

### CODE REVIEW

**Review by Marterich — CHANGES_REQUESTED** [review]
In my opinion it is a dangerous assumption to make that all Win10 and Win11 installs with winget also have the Cmdlets installed. 
I've just spun up a new Win11 VM and winget was installed, but the Cmdlets were not. In this case, the winutil would now be useless until the user fixes the missing dependencies manually. All in all I'm not against using the Cmdlets but I think a bunch of legwork has to be done to make sure fallbacks are in place for when the Cmdlets are missing. (e.g. auto install the cmdlets or fallback to using the executable). I've written a commend I a previous PR already about the problems using Cmdlets https://github.com/ChrisTitusTech/winutil/pull/1682#discussion_r1527164290

**Comment by ruxunderscore** [comment]
> In my opinion it is a dangerous assumption to make that all Win10 and Win11 installs with winget also have the Cmdlets installed. 
> I've just spun up a new Win11 VM and winget was installed, but the Cmdlets were not. In this case, the winutil would now be useless until the user fixes the missing dependencies manually. All in all I'm not against using the Cmdlets but I think a bunch of legwork has to be done to make sure fallbacks are in place for when the Cmdlets are missing. (e.g. auto install the cmdlets or fallback to using the executable). I've written a commend I a previous PR already about the problems using Cmdlets https://github.com/ChrisTitusTech/winutil/pull/1682#discussion_r1527164290
> 

Ah, yes. I did mean this as an addition to my other fix, which should always fetch the newest version of WinGet, but even then your change is a great addition. Thank you!

**Comment by Marterich** [comment]
I just spun up a Win11 VM again to test if the Cmdlets will be installed automatically together with the newest winget release (v1.7.10861) downloaded and installed directly from the winget-cli gh repo but it still seems that **the Cmdlets won't be installed automatically** so if you want to utilize this functions, maybe the following snipped I wrote might be a good starting point to extend your PR to auto-update winget and install the cmdlet as well. 
I have no time to write and test a full PR including error handling etc at the moment and contextually it fits into your PR so maybe you want to give it a go :)

```powershell
$response = Invoke-RestMethod -Uri "https://api.github.com/repos/microsoft/Winget-cli/releases/latest" -Method Get -ErrorAction Stop
$installer = $response.assets | Where-Object {$_.name -eq "Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle"} | Select-Object Name, browser_download_url, @{Name = "path"; expr = {"$ENV:TEMP\"+$_.name}} 

Write-Host "Downloading", $installer.name, "..."
Invoke-WebRequest -Uri $installer.browser_download_url -OutFile $installer.path 

Write-Host "Installing", $installer.name, "..."
Add-AppxPackage -Path $installer.path -ForceUpdateFromAnyVersion

Install-PackageProvider -Name NuGet -Force
Install-Module -Name Microsoft.WinGet.Client -Force
```

**Comment by ruxunderscore** [comment]
> I just spun up a Win11 VM again to test if the Cmdlets will be installed automatically together with the newest winget release (v1.7.10861) downloaded and installed directly from the winget-cli gh repo but it still seems that **the Cmdlets won't be installed automatically** so if you want to utilize this functions, maybe the following snipped I wrote might be a good starting point to extend your PR to auto-update winget and install the cmdlet as well. 
> I have no time to write and test a full PR including error handling etc at the moment and contextually it fits into your PR so maybe you want to give it a go :)
> 
> ```powershell
> $response = Invoke-RestMethod -Uri "https://api.github.com/repos/microsoft/Winget-cli/releases/latest" -Method Get -ErrorAction Stop
> $installer = $response.assets | Where-Object {$_.name -eq "Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle"} | Select-Object Name, browser_download_url, @{Name = "path"; expr = {"$ENV:TEMP\"+$_.name}} 
> 
> Write-Host "Downloading", $installer.name, "..."
> Invoke-WebRequest -Uri $installer.browser_download_url -OutFile $installer.path 
> 
> Write-Host "Installing", $installer.name, "..."
> Add-AppxPackage -Path $installer.path -ForceUpdateFromAnyVersion
> 
> Install-PackageProvider -Name NuGet -Force
> Install-Module -Name Microsoft.WinGet.Client -Force
> ```

Thank you! I'll take a look when I get off work!

**Review by ChrisTitusTech — APPROVED** [review]

**Comment by ChrisTitusTech** [comment]
Do we want to merge this and add the improvement to the installer in another PR or add it to this one? @ruxunderscore

**Comment by ruxunderscore** [comment]
@ChrisTitusTech Let's hold this back and I can work on these tonight.

**Comment by ruxunderscore** [comment]
This should be the final update. @Marterich I implemented your suggestion during the winget-cli install. I also changed some commands to work better after a bit of testing on clean Windows VMs.

**Comment by ruxunderscore** [comment]
@ChrisTitusTech This should be good to merge into the test branch now. I got the code tidied up and better tested.

**Comment by ChrisTitusTech** [comment]
> @ChrisTitusTech This should be good to merge into the test branch now. I got the code tidied up and better tested.

Awesome thanks Rux!

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
