### PR TITLE
fix: missing `-AND` and inconsistent formatting

### PR DESCRIPTION
**Pull request by Malix-Labs**
## Type of Change
- [ ] New feature
- [X] Bug fix
- [ ] Documentation update
- [X] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description

This pull request fix a missing `-AND` and make make the formatting of all `-AND` consistent

## Testing

None needed

## Impact

Minor

## Checklist
- [X] My code adheres to the coding and style guidelines of the project.
- [X] I have performed a self-review of my own code.
- [X] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Review by ruxunderscore — APPROVED** [review]

**Review by Real-MullaC — APPROVED** [review]

**Comment by Real-MullaC** [comment]
@CodingWonders Please do a check to make sure it is fine.

**Review by CodingWonders — APPROVED** [review]
I didn't notice that missing -AND. Thanks, @Malix-Labs!

**Comment by Malix-Labs** [comment]
You're welcome @CodingWonders ! :heart:

**Comment by cursedUs64-git** [comment]
Anyone still paying attention to this? The pull was not pushed to the repo, due to @Malix-Labs deleting the head repository for this pull. Please, someone push this to the repo

**Comment by Malix-Labs** [comment]
I mistakenly took the approved for a merge, sorry about that

**Comment by Malix-Labs** [comment]
a

**Pull request closed without merging**
