### PR TITLE
Fix typo in Remove-Packages

### PR DESCRIPTION
**Pull request by leonardo-dgs**
## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] Documentation update
- [x] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
Fix typo in Remove-Packages function: `"*indows-Client-LanguagePack*"` instead of `"*Windows-Client-LanguagePack*"`

### CODE REVIEW

**Comment by CodingWonders** [comment]
@leonardo-dgs, it has wildcard characters. It will always spot `Windows-Client-LanguagePack` without this change

**Comment by CodingWonders** [comment]
It's not a big deal though. It looks nice and, if it still works, it can be merged. Have you made a test image with your change and verified that it works correctly, @leonardo-dgs?

**Comment by MyDrift-user** [comment]
Powershell string comparison operators are usually not case sensitive, maybe that was the thought behind starting with *i.

**Comment by leonardo-dgs** [comment]
I've tested, and it works

**Pull request closed without merging**
