### PR TITLE
Merge 'pre-release', 'release', and 'Compile' Workflows into one workflow - Fixes 'Release WinUtil' Workflow & Removes 'winutil.ps1' From Git Tracking List

### PR DESCRIPTION
**Pull request by og-mrk**
## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Documentation update
- [x] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
~Copy-Pasted some things from 'pre-release' workflow, and learned a few things from it (like Environment Variables and how they're shared across steps in GitHub Actions), as well as make sure that both work as expected.~ _Old PR Purpose_

After a bit of tinkering here & there, I was able to get Input Workflow Working, you can now choose if you want to release WinUtil as a Stable Release or as a Pre-Release (default is Pre-Release).

Also there has been alot of changes to how WinUtil is deployed, which's converting from the old Test & Stable Git Branches with Direct Linking to `winutil.ps1` file on GitHub, to a more Standardized Deployment System (Using GitHub Actions & GitHub Releases), Because of this.. the compiled file `winutil.ps1` on the main branch **will be removed**, as it's **no longer needed**, it isn't referenced anymore, through the docs, project source code, nor through `christitus.com/win` web re-direct (it now redirects to a specific Release on GitHub (new method), rather than `winutil.ps1` on main branch (old method)).

## Testing
After alot testing, I got it working pretty well, I haven't noticed any issues in the logs, nor did I see any error in Release Title & Description.

One minor exception is when you Release twice in the same day.. the release body & generated notes of second run _will be appended_ to the previous run.. which is something to look at (can be easily fixed by making `append_body` field equal `false` in the last step (the release step) of `release.yml` workflow, haven't changed it as I thought you want this behavior.. so I left it as is)

## Impact
Will make it possible to use the 'Release WinUtil' Workflow, and it'll make other issues like Auto-Compile & Commit action less annoying on Forks (all workflows are enabled by default, and you'll need to disable it.. not very intuitive to be honest)

## Additional Information

> [!NOTE]
> I'm still new to this GitHub Actions thing.. so if you notice anything odd, feel free to point it out, thanks in advance 👍

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by og-mrk** [comment]
After further inspection of these two workflow files.. they're _almost_ identical to one another, to the point where I'm questioning if there's a reason of having two workflow files instead of one (which has some input parameters, which'll allow you to make the release a Pre-release or a Full Stable Release), _**screenshot proving my point**_.

image

**Comment by og-mrk** [comment]
@ChrisTitusTech @Real-MullaC @MyDrift-user @Marterich @CodingWonders and anyone who's interested on these changes, especially the removal of `winutil.ps1` from Git Tracking List.

First, my bad for pinging you guys, I just wanted to inform the most active contributors about this, as it's a step _I believe_ is necessary, which's updating your Local Git Cache, you can do this by running two commands:
```sh
cd Path/To/Local/WinUtilRepo
git rm -r --cached .
git add .
```
> 1. First Command changes your working directory to be your Locally Cloned WinUtil Repo (the `Path/To/Local/WinUtilRepo` part).
> 2. The second is `git rm -r --cached .`, which'll remove every file from the current directory (which's WinUtil Root Directory) from **Git Tracking Cache**, this's needed whenever you updated `.gitignore` file, but the ignored folder(s)/file(s) are already tracked.. so you need to clear the cache.
> 3. You'll need to add every file, as git will see every single file as Un-tracked file (new files), so you need to tell it "Hay Git, please track these files" by running `git add .`, where `.` is WinUtil Root Directory.

</br>

I hope this helps out, and if you've any question about it, feel free to post it, and I'll reply when I can. Have a nice day 😄

**Comment by og-mrk** [comment]
Also @ChrisTitusTech , if you find any changes to be odd in these changes, feel free to change it by editing the file on GitHub, and committing it to my branch.

image

**Comment by CodingWonders** [comment]
> especially the removal of `winutil.ps1` from the Git Tracking List

@og-mrk, every time `winutil.ps1` appeared in the changes list, I would simply tell Git to assume that the file never changed with this command:

`git update-index --assume-unchanged .\winutil.ps1`

However, this seems like a more permanent solution

**Comment by Marterich** [comment]
@og-mrk please keep in mind, that the pre-release script also used different tags (with the prefix pre-) this had a simple reason.

If Chris would create a full release in the morning and a pre-release later that day, the full release would be converted to a pre-release again (becaus the same tag was used)

Haven't checked out your code too closely, but do you handle the case, that a full release with the same tag already exists when a new pre-release is added so that the full release doesn't get overwritten?

**Comment by og-mrk** [comment]
> @og-mrk please keep in mind, that the pre-release script also used different tags (with the prefix pre-) this had a simple reason.
> 
> If Chris would create a full release in the morning and a pre-release later that day, the full release would be converted to a pre-release again (becaus the same tag was used)
> 
> Haven't checked out your code too closely, but do you handle the case, that a full release with the same tag already exists when a new pre-release is added so that the full release doesn't get overwritten? 
> 

Will check this edge case today when I get home. Thanks for the feedback @Marterich 😄

**Comment by og-mrk** [comment]
As removing `winutil.ps1` in this PR results in merge conflicts (meaning it can't be merged to main branch).. I'll make removal of this file in a separate PR entirely, where when every other PR is closed, it'll be the last one to be merged on the review batch.

Reverting commit 0fa13254f1692fc4ff0898381b0abe8ebdcc279f

**Comment by ChrisTitusTech** [comment]
I like having these job separated. I don't want to have anything with the Compile and most time I will use the pre-release and change it to a full release after it has been tested.

**Comment by Marterich** [comment]
> I like having these job separated. I don't want to have anything with the Compile and most time I will use the pre-release and change it to a full release after it has been tested.

@ChrisTitusTech In that case, would it be an option to completely remove the full release action if it's not really used anyways?

**Pull request closed without merging**
