### PR TITLE
Added tweaks for IPv6

### PR DESCRIPTION
**Pull request by Joanty24**
Added tweaks to disable and enable IPv6.

### CODE REVIEW

**Review by ChrisTitusTech — APPROVED** [review]

**Comment by ChrisTitusTech** [comment]
I might actually change this to a different section like config instead of tweaks. I'll probably push DNS over there too. It makes more sense in the other tab. I'm about to revamp the tweaks/config section to be more user friendly.

**Comment by Joanty24** [comment]
If you want I can move it to the config tab but I'd keep it as it is until the GUI update.  
I'll do what you thing is best.

**Comment by ChrisTitusTech** [comment]
> If you want I can move it to the config tab but I'd keep it as it is until the GUI update. I'll do what you thing is best.

I'm just thinking of the most user friendly way of approaching it. I am going to remove all the "Disable/Enable" Tweaks and make those toggles. Ipv6 will be one of those. You can see Dark Mode as a reference.

**Review by ChrisTitusTech — APPROVED** [review]

**Comment by ChrisTitusTech** [comment]
Going to just merge it so the code is there and I'll move it later.

**Pull request merged**
