### PR TITLE
Update PULL_REQUEST_TEMPLATE.md to link the contribute page

### PR DESCRIPTION
**Pull request by Real-MullaC**
# Pull Request

## Title
Update PULL_REQUEST_TEMPLATE.md to link the contribute page

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [x] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
Update PULL_REQUEST_TEMPLATE.md to link the contribute page

## Testing
None required

## Impact
High as it makes sure all PR's are done correctly.

## Issue related to PR
[What issue/discussion is related to this PR (if any)]
- Resolves no issues

## Additional Information
Nope

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Review by CodingWonders — APPROVED** [review]
A necessary change to make contributing easier for newcomers. I like it!

**Comment by MyDrift-user** [comment]
testing smth out

**Comment by Real-MullaC** [comment]
> @Real-MullaC While reading this change and the current template I saw that there are many infos for the PR creator that are not important to the reviewer (most stuff in [ ] ). For that we could use markdown comments, they work as intendet in github conversations ... and are visible in the editor, but not in the finished PR Description that u see when not editing the description. What do you think about it? how to do it: { `<!-- This is a comment in Markdown -->` } how it looks while not editing: {
> 
> }

Changed

**Comment by Real-MullaC** [comment]
> could you please also do this with everything that is in "[ ]"

Done

**Review by MyDrift-user — APPROVED** [review]
Thanks, looks great now

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
