### PR TITLE
Add missing program in applications.json file

### PR DESCRIPTION
**Pull request by padsalatushal**

### CODE REVIEW

**Comment by padsalatushal** [comment]
@DeveloperDurp  I added  missing programs in the application.json file

**Comment by DeveloperDurp** [comment]
Could you try running the application json through the helper script? Something is off with the formatting in your file and it's causing github to see a large number of changes.

**Comment by padsalatushal** [comment]
@DeveloperDurp Actually it is my fault I guess because I messed up with the git command and after that, I had to delete the branch and create a new then  manually copy the content of the file and paste over it on the application.json file

**Comment by DeveloperDurp** [comment]
Yeah, i was having some issues too. I think this might be the process to follow.

1. Fork the winutil repo
2. Inside your repository create a branch (Call it something relevant IE I like to do feature/whatiamdoing)
3. clone the code to your machine and checkout that branch. (git checkout *BranchName*)
4. run `git pull upstream main-test`
5. make your changes and commit up to your repository
6. From here create a PR to merge into winutil and choose your branch instead of the main branch. 
7. Once it gets merged delete the branch from your repository

I will also look into this 
https://phoenixnap.com/kb/git-set-upstream

might be possible you can change the upstream of your main branch to look at the winutil/main-test branch to keep things in sync better.

**Comment by padsalatushal** [comment]
@DeveloperDurp Thanks..

**Comment by padsalatushal** [comment]
@ChrisTitusTech  This PR is merged but I can't see these changes in any branch. Should I have to create a new PR?

**Comment by DeveloperDurp** [comment]
There was an issue with a merge, you will need to create a new PR unfortunately

**Pull request merged**
