### PR TITLE
Functions and error handling

### PR DESCRIPTION
**Pull request by DeveloperDurp**
Working on moving some functions of the script into functions for easier pester testing and adding error handling

### CODE REVIEW

**Comment by DeveloperDurp** [comment]
benefit of the new start-process method is you don't need to start this application as admin (though choco will fail as it doesn't use this process)

**Comment by DeveloperDurp** [comment]
@Carterpersall I think you will like this commit 

https://github.com/ChrisTitusTech/winutil/pull/552/commits/2935ba931a1483365e2c7d9f7f72f27fa1c46eeb

**Comment by DeveloperDurp** [comment]
@ChrisTitusTech I moved this PR out of a draft phase, looking at improving the tweaks section it's going to be fairly large so I will have a dedicated PR for that.

**Review by ChrisTitusTech — APPROVED** [review]
Looks good!

**Pull request merged**
