### PR TITLE
Color fixes in the UI. 

### PR DESCRIPTION
**Pull request by SHR1SHAK**
Fixed some colors which helps in better color contrast and fixed the text under the Update tab where the description is called default color. Added style to Textblock.

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [x] UI/UX improvement

## Issue related to PR

- Resolves #

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by SHR1SHAK** [comment]
image
Left is before | Right is after fix

**Comment by SHR1SHAK** [comment]
image
fixed border visibility and color of the header

image
Fixed color of DNS Button

**Review by ChrisTitusTech — APPROVED** [review]
Thanks for the fixes, but for the future remove your formatter or prettier. This will be wiped out by the precompiler and the added whitespace would be typically denied. 
Also it makes your changes harder to read which usually leads to a denied PR.

**Comment by SHR1SHAK** [comment]
Sorry for that, I will have exclusion on this project for future updates

**Comment by Real-MullaC** [comment]
> Thanks for the fixes, but for the future remove your formatter or prettier. This will be wiped out by the precompiler and the added whitespace would be typically denied. Also it makes your changes harder to read which usually leads to a denied PR.

The whitespace removal was from the remove whitespace script. I think.

**Comment by Real-MullaC** [comment]
> > > Thanks for the fixes, but for the future remove your formatter or prettier. This will be wiped out by the precompiler and the added whitespace would be typically denied. Also it makes your changes harder to read which usually leads to a denied PR.
> > 
> > 
> > The whitespace removal was from the remove whitespace script. I think.
> 
> i have prettifier extension on my vscodium so when I save it auto prettifies the code. I have already excluded this project now for the future update.

Ok

**Pull request merged**
