### PR TITLE
Create Coplotremove.ps1

### PR DESCRIPTION
**Pull request by Nikoskampourakis**
That script removes copliot btw.ots powershell

### CODE REVIEW

**Comment by Nikoskampourakis** [comment]
gh pr checkout 2289

**Review by Real-MullaC — CHANGES_REQUESTED** [review]
That is not the only code that is needed that is part of it. Please see other files to know what to add. 

I would tell you but it is hard to see on mobile. As on Holiday.

**Review by KonTy — CHANGES_REQUESTED** [review]
why do we need a separate ps1 file, what will be randomely placed in the repo? This file is not downloaded with winutil and will not be accessible usable. We do have a tweak that remove copilot, if it is outdated or doesn't do the right thing, please update it instead of placcing a random file in the repo.

**Comment by Nikoskampourakis** [comment]
Because thats how winutil works by ps1 files because it can run scripts which we can customise and remove bloat and make windows more useful and usable

**Comment by Nikoskampourakis** [comment]
And i want to add a way to remove copliot and bing ai so theres alternative to remove copliot by clicking a button and never seen it again so wont switch to linux

**Comment by Nikoskampourakis** [comment]
Ps1 files are powershell script that do the tweaks and winutil is 98.4 present powershell and there all most ps1 and different types of files so yes there aren't placed the are generated and this ps1 file is for tweak that you can import the other one is editing windows and made to install and uninstall the program

**Comment by Nikoskampourakis** [comment]
Real mulla c tell me then what files should i add and code i will try to code it and try to putt it on the winutil so i can be a contrybutor

**Comment by Real-MullaC** [comment]
> Real mulla c tell me then what files should i add and code i will try to code it and try to putt it on the winutil so i can be a contrybutor

1. That file is not needed.
2. You have to edit file config/tweaks.json

**Review by ChrisTitusTech — CHANGES_REQUESTED** [review]
I'd rather this all be done in Tweaks.json than doing separate functions. We already have a Disable CoPilot tweak and it just needs to be expanded.

**Comment by Nikoskampourakis** [comment]
Hey guys i didn't tested the tweak yet but the problem is that i can't upload it as a zip file i have a picture that the tweak in virus total can someone test my ps1 tweak its about removing copliot ai permanently even windows update 
[Coplotremove.ps1.zip](https://github.com/user-attachments/files/16120664/Coplotremove.ps1.zip)

**Comment by Nikoskampourakis** [comment]
Btw i didn't mention it that i don't have a windows pc

**Comment by Nikoskampourakis** [comment]
And made a earlile GitHub https://github.com/Nikoskampourakis/Copliot-removal-/blob/main/Copliotdisable.ps1 if you know what is doing

**Comment by Nikoskampourakis** [comment]
Tell me any issues about the script if it has bugs tell me on GitHub

**Comment by Real-MullaC** [comment]
> Tell me any issues about the script if it has bugs tell me on GitHub link https://github.com/Nikoskampourakis/Copliot-removal-/blob/main/Copliotdisable.ps1

You need to put it into the config folder then in tweaks.json file find the bot about removing copilot and etc then putting your code there correctly. Not have a separate file.

**Comment by Nikoskampourakis** [comment]
I don't need a bot its on group pollicy editor i tweaked it

**Comment by Nikoskampourakis** [comment]
> > Tell me any issues about the script if it has bugs tell me on GitHub link https://github.com/Nikoskampourakis/Copliot-removal-/blob/main/Copliotdisable.ps1
> 
> You need to put it into the config folder then in tweaks.json file find the bot about removing copilot and etc then putting your code there correctly. Not have a separate file.

I already have an alternative here i already have the script {
  "WPFCopliotremovepermanent": {
    "Content": "Disable Windows Copilot",
    "Description": "This disables Windows Copilot permanently even if windows updates.",
    "category": "Essential Tweaks",
    "panel": "1",
    "Order": "a005_",
    "url": "https://github.com/Nikoskampourakis/Copliot-removal-/blob/main/Copliotdisable.ps1"
  }
}

**Comment by Nikoskampourakis** [comment]
The code for the tweak is in the GitHub and thx again

**Pull request closed without merging**
