### PR TITLE
Remove oosu essential tweak

### PR DESCRIPTION
**Pull request by Marterich**
Resolves: #2085

As explained in the Linked Issue, I think the time has come to remove the OOSU Checkbox from the Essential Tweaks.
The Button under Advanced Tweaks remains, but the wording was changed so that it makes more sense even without the previous simple checkbox tweak. 

- It was unclear to the users what changes were applied by the function which generated lots of Issues regarding disabled functionality. 
- OO Software seems to have included more functionality that users actually want to use in their "recommendations"

For the full reasoning behind this change, please take a look at the Issue.  #2085

Prevents issues like this in the future
Closes: #2047
Closes: #2027
Closes: #2012

### CODE REVIEW

**Comment by og-mrk** [comment]
The changes look great, and it's quite nice of you to propose the idea _first_ to get feedback from other users and contributers 👍

I guess that the `.cfg` files in `config` folder is not needed if this PR gets merged, may be removing those `.cfg` is worth doing? To remove unused files and drope support for them (still remember that O&O Shutup didn't work for a long time, up until the config files got updated 😅

It could be removed in a separate PR.. but I don't see why it wouldn't be possible to do it here.. but anyhow, good work as always @Marterich 👍

**Comment by Marterich** [comment]
> The changes look great, and it's quite nice of you to propose the idea _first_ to get feedback from other users and contributers 👍
> 
> I guess that the `.cfg` files in `config` folder is not needed if this PR gets merged, may be removing those `.cfg` is worth doing? To remove unused files and drope support for them (still remember that O&O Shutup didn't work for a long time, up until the config files got updated 😅)
> 
> It could be removed in a separate PR.. but I don't see why it wouldn't be possible to do it here.. but anyhow, good work as always @Marterich 👍

> If you look real close at the changed files you can see that the files are removed as well 😜
The only thing I didn't remove was the cfg parsing bit in the compile script

**Comment by og-mrk** [comment]
> > The changes look great, and it's quite nice of you to propose the idea _first_ to get feedback from other users and contributers 👍
> > 
> > I guess that the `.cfg` files in `config` folder is not needed if this PR gets merged, may be removing those `.cfg` is worth doing? To remove unused files and drope support for them (still remember that O&O Shutup didn't work for a long time, up until the config files got updated 😅)
> > 
> > It could be removed in a separate PR.. but I don't see why it wouldn't be possible to do it here.. but anyhow, good work as always @Marterich 👍
> 
> If you look real close at the changed files you can see that the files are removed as well 😜
> The only thing I didn't remove was the cfg parsing bit in the compile script

Yahh I just noticed that 😂 viewing Git patches in the middle of the night (inside a smartphone) is not the best thing to do 😅

Also the compile bit could be done quite easily (_famous last words_), I'll make a PR to your Fork, give me a minute while I open my laptop...

**Review by ChrisTitusTech — CHANGES_REQUESTED** [review]
We had some changes to the compile script and I believe this one isn't up to date with that. Can you pull the changes and recommit?

**Review by ChrisTitusTech — APPROVED** [review]

**Comment by 4yman-el** [comment]
Niiiiice! :rocket:

**Pull request merged**
