### PR TITLE
Add listary to utilities

### PR DESCRIPTION
**Pull request by lukevanlukevan**
## Type of Change
- [x] New feature
- [ ] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
I have added [Listary](https://www.listary.com/) to the Install page, grouped under Utilities. It is a useful file browser addon with a very powerful and fast search window.

## Testing
N/A, but I have also confirmed both the winget and choco install strings

## Impact
This will add Listary as am option in the install page, under Utilities.

## Issue related to PR
No issue

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by lukevanlukevan** [comment]
i see my code uses tabs vs spaces. I will adjust formatting when I next can

**Comment by Real-MullaC** [comment]
Why was all the lines changed? Also we are not adding applications at the moment.

**Comment by lukevanlukevan** [comment]
> Why was all the lines changed? Also we are not adding applications at the moment.

Sorry, mentioned in my second comment. Formatting error by prettier, I'll adjust as soon as I can

**Comment by Real-MullaC** [comment]
This PR will not be merged anyway as we are not adding any applications anyway.

**Pull request closed without merging**
