### PR TITLE
Complete Winget Install Overhaul and Progress Bar in GUI

### PR DESCRIPTION
**Pull request by Marterich**
## Type of Change
- [x] New feature
- [x] Refactoring
- [x] UI/UX improvement

## Description

- Complete Rework (and Rename) of the Winget install Function. 
- Adds a Progress Bar in the UI that shows the status of (e.g running installs) hidden If nothing is going on 
image
- smaller cleanups and changes I encountered along the way

### Note
To be fair, I should have probably split this up into multiple PRs, but I got a bit carried away while creating this when I realized how badly the winget install logic was put together and that it would have been subjectively more work implementing the changes to the old one than just rewriting it completely. Then one thing led to another and now we are here...
 
## Testing
Tested extensively on my Win11 23H2 VM but as this is quite the overhaul, more testing is recommended.

## Impact
Provides a nicer way of displaying what is going on to the user and lays the foundation for completely removing the necessity of displaying the open Powershell session beside the main window.

The rework of the winget program install logic provides a more solid base to extend it in the future and also fixes the need for passing PSCustomObjects to the Install Logic for winget. Now a list of IDs is sufficient.  

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.

### CODE REVIEW

**Comment by MyDrift-user** [comment]
Hey @Marterich, it looks like you removed the existing progress bar for applications with this PR, but I did not look that deep into it. Is this intended or was it overlooked?

**Comment by Marterich** [comment]
> Hey @Marterich, it looks like you removed the existing progress bar for applications with this PR, but I did not look that deep into it. Is this intended or was it overlooked? Otherwise looks good, will test it out later.

The Taskbar Update is still in there and now needs only a single line to be applied. 
Just fixed the range for the value of the taskbar item. Didn't realize that it only needs numbers between 0 and 1.

**Comment by MyDrift-user** [comment]
This also fixes an issue with the taskbaritem that occurred by merging mine and another PR. This will fix the overlap.

Thanks @Marterich

**Review by ChrisTitusTech — APPROVED** [review]
I have been trying to do this for over 2 years... Well done @Marterich 
Simply amazing.

**Pull request merged**
