### PR TITLE
Refactor/runspaces

### PR DESCRIPTION
**Pull request by DeveloperDurp**
Found a more stable way to use runspaces, going to make these changes to the runspace.ps1 file as well as having it compile all the functions into one file for a cleaner repo.

### CODE REVIEW

**Comment by ChrisTitusTech** [comment]
Looking forward to trying this out. I'm going to be livestreaming updates Monday, Tuesday, and Thursday for the toolbox next week on Twitch: <https://www.twitch.tv/christitustech>
Tons of things to test and improve based on all your PR's Durp! Thanks so much and all these should be cleaned up by the end of next week.

**Review by ChrisTitusTech — COMMENTED** [review]
A lot going on with this PR. I'm not sure if being this modular would be beneficial for long term development. 
Are the speed improvements worth it?

**Comment by DeveloperDurp** [comment]
Modular files are mostly to make things easier to manage with multiple people contributing to the code.  

The compile.ps1 pulls everything and throws it into runspace.ps1 including the xaml and configs so it doesn't need to rely on github to pull that.

If you would rather stick to one large file you can run the compile once and the runspace.ps1 will be the updated file and you can delete the extra folders

**Review by ChrisTitusTech — APPROVED** [review]
Let's give it a shot on test and see how the modular system works. I see your point with using it for maintenance.

**Pull request merged**
