### PR TITLE
Change the Theme Configuration for low spec.

### PR DESCRIPTION
**Pull request by blusewill**
I modified the Theme in Dark Mode since is Resource intensive
It makes the problem in #1441 and #1423 better by disabling the glow color when detected only on board graphics
Which is the File  `Invoke-WinUtilGPU.ps1` does.
Checking for the GPU is detected or not
If not it will fallback to the Lite Dark Theme which is specific in the `theme.json`
There is no point to change the Classic Theme due to is already lite enough that won't uses many process.

### CODE REVIEW

**Comment by KonTy** [comment]
This is not a PowerShell issue, this is literally low spec issue :) What I did is buried an easter egg in the code where the glow was pulsating, I wanted to remove it but forgot to do it. Since on my machine I don't notice any difference. @blusewill there is a much easier way to disable the shadow pulse. In the theme.json there is a variable called
``
"ShadowPulse": "0:0:3"
``

if you change it "Forever" it will stop pulsing and taxing your machine.

**Comment by blusewill** [comment]
@KonTy Well Yes if you check the code I make another Theme called Dark. 
But I don't want to disable the glow color so I decided to make a detection of the Graphic driver is done or not.
And the other configuration in the theme.json is copied from classic theme due to classic theme is light enough.

**Review by ChrisTitusTech — APPROVED** [review]

**Comment by bdebates** [comment]
This is an issue! I have a quadro rtx 4000 and it is using 70% of my GPU.  When I tried searching for GPU related issues I came across issue 1423. Someone in that issue had their 6950XT was sitting at almost 50%. Another person had their 3070 mobile sitting at 34%. This issue was closed due to inactivity. Now that i finally was able to track this down, I see there are a couple of issues related to this. 

This was all because _one_ person (@KonTy ) wanted pulsating text and snuck a huge performance bug into the code as an "Easter Egg"? 

This is ridiculous and needs to either be completely removed or toggle able, because our measly GPUs pass your "check" when they aren't good enough for your pulsating text.

**Comment by blusewill** [comment]
In the future update might have a toggle for the Dark Mode or Matrix.
But for now you can Download Winutil and Modify the Code it self also would work.

**Pull request merged**
