### PR TITLE
Create Invoke-ScratchDialog.ps1

### PR DESCRIPTION
**Pull request by LeeDowA**
function file

### CODE REVIEW

**Comment by KonTy** [comment]
@LeeDowA do you work for facebook or something? :) We do pull requests per logic unit/topic all your prs will work only togeather why split them into multiple prs?

**Comment by LeeDowA** [comment]
I know. But i did not know how to post all the changes together :). \_/

**Comment by KonTy** [comment]
> I know. But i did not know how to post all the changes together :). _/

Thank you for your contributions :)

**Comment by ChrisTitusTech** [comment]
Thanks for the contributions but I can't accept them in their current form. These should have been in 1 PR that I could test before merging into our test branch. 
Also, these were commited to main which I don't accept PR directly to. TEST Branch must be used. 
Closing all PRs.

**Pull request closed without merging**
