### PR TITLE
Update Phone Link Application ID in config/tweaks.json.

### PR DESCRIPTION
**Pull request by Cryostrixx**
# Pull Request

## Title
Update **Phone Link** Application ID in **config/tweaks.json**.

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
Change ID **Microsoft.WindowsPhone** to **Microsoft.YourPhone** and remove invalid ID **Microsoft.CommsPhone** in the **WPFTweaksDeBloat** function.
This fixes an issue where **Phone Link** was not getting uninstalled correctly when debloating the system using the **Remove ALL MS Store Apps** tweak.

## Testing
Tested the change locally by running the compiled script and confirming that the **Phone Link** (**Your Phone**) application was correctly removed.

## Impact
This change ensures the **WPFTweaksDeBloat** function uninstalls the correct **Phone Link** application and eliminates the redundant **Microsoft.CommsPhone** entry.

## Issue related to PR
None.

## Additional Information
None.

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by Real-MullaC** [comment]
I just looked in WinGet and none of them seem to be any packages.

**Comment by Cryostrixx** [comment]
> I just looked in WinGet and none of them seem to be any packages.

Hello, Real-MullaC!

I double-checked, and the application ID you mentioned is part of the WPFTweaksDeBloat function. Microsoft.YourPhone is not an installable app; it's meant to be removed when you select "Remove All MS Store Apps" in the "Tweaks" tab. I hope this clarifies things!

**Comment by Real-MullaC** [comment]
> > I just looked in WinGet and none of them seem to be any packages.
> 
> Hello, @Real-MullaC!
> 
> I double-checked, and the application ID you mentioned is part of the WPFTweaksDeBloat function. Microsoft.YourPhone is not an installable app; it's a system-level app meant to be removed when you select "Remove All MS Store Apps" in the "Tweaks" tab. I hope this clarifies things!

The tweaks file is used to run Winget commands to install and unistall apps. And I have had a look and none of the variables you entered and deleted are within WinGet.

**Comment by Cryostrixx** [comment]
Hi Real-MullaC,

The application IDs you’re asking about are handled by the `WPFTweaksDeBloat` function in the script. This function is used for removing unwanted apps and is not related to package managers like `WinGet`, `Chocolatey`, or `Scoop`. These IDs are part of the debloat process and are not standalone installable packages.

To clarify:
* The `tweaks.json` file, particularly in the `WPFTweaksDeBloat` section, is used to run commands that uninstall apps through `Remove-AppxPackage`. The IDs you're inquiring about are managed by this function for the debloat functionality.
* For installing software, the configurations are found in `applications.json`, which is separate from the debloat script (`WPFTweaksDeBloat`) in `tweaks.json`.

I’ve attached the relevant output of `Get-AppxPackage` to help illustrate this.
[Get-AppxPackage output showing that Your Phone is a system-level app](https://github.com/user-attachments/files/16483029/Microsoft.YourPhone_Installed.txt).

I hope this helps further clarify things!

**Comment by Real-MullaC** [comment]
If you looked more closely into the fellow scripts you will find Winget is used for them. To uninstall the packages.

**Comment by Cryostrixx** [comment]
Hi Real-MullaC,

I understand your point, but I’d like to clarify that WinGet is not used for uninstalling .appx or .msixbundle packages. The WPFTweaksDeBloat function in the script operates through PowerShell commands like Remove-AppxPackage to handle these types of packages, which are not managed by WinGet.

For uninstalling applications managed by WinGet, the tool is indeed utilized, but this does not apply to .appx or .msixbundle files, which are handled separately.

Given the specifics of how this script works, it might be more effective for someone with a deeper understanding of the project to review the changes.

Thank you for your patience and understanding.

Best regards,
Cryostrixx

**Review by og-mrk — APPROVED** [review]
Hello @Cryostrixx 
After further looking into your changes, and checking if AppX IDs match with what's found on Windows 10 & 11... I can say that indeed the new ID for `YourPhone` App is found in AppX Packages List, plus the AppX ID `Microsoft.CommsPhone` is either a deprecated package, or a simple typo made while making this list, therefore removing it from this list is best course of action, at least IMHO.

-------

For anyone who want to verify this as well, run the follow command inside a PowerShell Terminal running as **Admin**:
```ps1
Get-AppxPackage -AllUsers | where { $_.Name -Like "*Phone*" }
```

The output should be something like:
```ps1
RunspaceId             : A-GUID-HERE
Name                   : Microsoft.YourPhone
Publisher              : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
PublisherId            : 8wekyb3d8bbwe
Architecture           : X64
ResourceId             :
Version                : 1.24062.101.0 <-- This could be different depending on the version of installed 'YourPhone' app
PackageFamilyName      : Microsoft.YourPhone_8wekyb3d8bbwe
PackageFullName        : Microsoft.YourPhone_1.24062.101.0_x64__8wekyb3d8bbwe
InstallLocation        : C:\Program Files\WindowsApps\Microsoft.YourPhone_1.24062.101.0_x64__8wekyb3d8bbwe
IsFramework            : False
PackageUserInformation : {S-AN-ID-DIFFERENT-FROM-ONE-PC-TO-ANOTHER [YOUR-PC-NAME\YOUR-USERNAME]: [Installed|Uninstalled]}
IsResourcePackage      : False
IsBundle               : False
IsDevelopmentMode      : False
NonRemovable           : False
Dependencies           : {Microsoft.VCLibs.140.00.UWPDesktop_14.0.33728.0_x64__8wekyb3d8bbwe, Microsoft.WindowsAppRuntime.1.5_5001.178.1908.0_x64__8wekyb3d8bbwe,
                         Microsoft.VCLibs.140.00_14.0.33519.0_x64__8wekyb3d8bbwe, Microsoft.YourPhone_1.24062.101.0_neutral_split.language-ar_8wekyb3d8bbwe…}
IsPartiallyStaged      : False
SignatureKind          : Store
Status                 : Ok
```

-------

Thanks for your contribution to WinUtil, and my apologies for any inconvenience(s) you may've faced during the review process...

**Review by ChrisTitusTech — APPROVED** [review]
Fantastic

**Pull request merged**
