### PR TITLE
Automatic elevation if powershell isn't already elevated

### PR DESCRIPTION
**Pull request by SchooiCodes**
# Pull Request

## Title
Automatic elevation if powershell isn't already elevated

## Type of Change
- [x] New feature
- [ ] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
Hey Chris, I thought it would be helpful if instead of the script saying that you need to restart as admin, it elevated itself. I have done this before in many batch scripts so I thought I found a way to do this in powershell too (I am a bit new to PS, although I have a lot of experience in batch, so if my code is bad, I am sorry in advance)

## Testing
I compiled it and I ran it, everything works fine.

## Impact
None

## Issue related to PR
None

## Additional Information
None

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by MyDrift-user** [comment]
heya @SchooiCodes, thanks for the PR
This functionality is already present in #2531 (if you want a change to his version, I advice suggesting it on his PR)

**Comment by SchooiCodes** [comment]
Sure, i just thought i would post this, this is much more compact and uses normal powershell which exists in all modern windows versions

**Comment by SchooiCodes** [comment]
I also added a choice so that the user can choose

**Comment by MyDrift-user** [comment]
The other one chooses powershell 7 (the better one) if available, if not it uses normal Windows Powershell.

The user choise is kind of redundant, because it opens the Window to allow/deny admin access, we could do a catch if the user sais no. I will suggest that in the other PR.

**Comment by SchooiCodes** [comment]
Hey, I fixed the choice, sorry it was late last night and i didn't remember to check if the user's choice was N. I am just updating cause I am bored, no need to use my PR if #2531 is better.

**Pull request closed without merging**
