### PR TITLE
Test 2024 01 03

### PR DESCRIPTION
**Pull request by ChrisTitusTech**
rework of unit tests... after 1billion commits lol. 
Program install details by @KonTy 
more microwin fixes by @CodingWonders

### CODE REVIEW

**Comment by KonTy** [comment]
@ChrisTitusTech  Let's go!!!

**Comment by JoKopii** [comment]
#1384, winutil line 931
Write-Host "File copied to Ventoy drive $($volume.DriveLette)"
probably missing a letter in volume.DriveLetter ?

**Comment by CodingWonders** [comment]
> #1384, winutil line 931 Write-Host "File copied to Ventoy drive $($volume.DriveLette)" probably missing a letter in volume.DriveLetter ?

There. [Fixed](https://github.com/ChrisTitusTech/winutil/pull/1727). Also, why in **this** PR (from 2 months ago), and not in a normal issue?

**Comment by JoKopii** [comment]
> > #1384, winutil line 931 Write-Host "File copied to Ventoy drive $($volume.DriveLette)" probably missing a letter in volume.DriveLetter ?
> 
> There. [Fixed](https://github.com/ChrisTitusTech/winutil/pull/1727). Also, why in **this** PR (from 2 months ago), and not in a normal issue?

im sorry, im not familiar with github 😅

**Pull request merged**
