### PR TITLE
Fix Dark Color Scheme

### PR DESCRIPTION
**Pull request by Marterich**
## Type of Change
- [x] UI/UX improvement

## Description

Most likely some of the Changes to the Theme were broken during some of the last commits, so here's my two cents on how to fix it (without actually taking the time and checking what settings were used before)

| Before    | After |
| -------- | ------- |
| image  | image    ||

### CODE REVIEW

**Comment by MyDrift-user** [comment]
I feel like tha background could be a bit darker than this.

**Comment by Marterich** [comment]
> I feel like tha background could be a bit darker than this.

It's actually the same as it is in the current stable release

**Comment by MyDrift-user** [comment]
Yeah ik I meant that, maybe not as dark as current main branch but a bit darker

**Comment by Marterich** [comment]
Let's leave the final design to our best maintainer :D

**Comment by SHR1SHAK** [comment]
Oh this broke again.

**Comment by SHR1SHAK** [comment]
@Marterich for color reference you can look youtube dark mode.

**Comment by SHR1SHAK** [comment]
DNS Button color also broke

**Comment by MyDrift-user** [comment]
It is the "Comboboxforegroundcolor" is used in many places, which is ducked up

**Comment by Marterich** [comment]
> It is the "Comboboxforegroundcolor" is used in many places, which is ducked up

Rly? Haven't seen it anywhere else while taking a quick peek

**Comment by SHR1SHAK** [comment]
i think we need to document what goes where for future ease.

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
