### PR TITLE
Removed small projects from applications.json

### PR DESCRIPTION
**Pull request by Owen-3456**
Removed the following projects:
- [ATLauncher](https://github.com/ATLauncher/ATLauncher) (600 Stars)
- [chromium](https://github.com/Hibbiki/chromium-win64) (400 Stars)
- [Windows Error Code Lookup](https://github.com/HenryPP/ErrorLookup) (200 Stars)

### CODE REVIEW

**Comment by gmcoding74** [comment]
@Owen-3456, I'm curious, why were these 3 projects chosen? Both Chromium and Error check (to me at least) seem like good things to keep in WinUtil. Just my two cents.

**Comment by Owen-3456** [comment]
> @Owen-3456, I'm curious, why were these 3 projects chosen? Both Chromium and Error code lookup (to me at least) seem like good things to keep in WinUtil. Just my two cents.

I just thought that these had quite a low star count and that the applications list is very bloated at the moment. I wont be offended if Chris doesnt agree.

**Comment by psyirius** [comment]
> > @Owen-3456, I'm curious, why were these 3 projects chosen? Both Chromium and Error code lookup (to me at least) seem like good things to keep in WinUtil. Just my two cents.
> 
> I just thought that these had quite a low star count and that the applications list is very bloated at the moment. I wont be offended if Chris doesnt agree.

Why does the GitHub star count matter for it to be useful to people?
Also, Chromium is developed completely offshore and it doesn't make sense to at least remove it's build variant.

**Review by ChrisTitusTech — APPROVED** [review]
Added Chromium back in because tons of people use that. However the others I agree can be removed.

**Pull request merged**
