### PR TITLE
Update PR: Add Uninstall CTT PowerShell Profile feature (#3012)

### PR DESCRIPTION
**Pull request by Cryostrixx**
## Type of Change

- [x] New feature
- [ ] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [x] UI/UX improvement

## Description

Makes some small fixes to my original PR that occurred as a result of conflict resolution.

### Additional Changes

* Removed the documentation files and links I added for PowerShell-Profile.
* Removed the Create WinUtil Shortcut feature that was removed in an earlier PR.

## Checklist

- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by Cryostrixx** [comment]
@og-mrk I think that's all of them, can you please review this and let me know if I need to make any other changes?

**Review by qusai-alaa — APPROVED** [review]

**Comment by Cryostrixx** [comment]
> These changes looks good to me, thanks @Cryostrixx 😄

Thanks for the feedback! If any other changes need to be made later, please feel free to @ me in the comments! :)

**Comment by MyDrift-user** [comment]
I am not sure if it is the fault of this PR, but when removing my powershell just stops working. terminal.exe, pwsh.exe and powershell.exe... even if running as admin.
An invisible window will appear if starting powershell / pwsh directly without terminal

image

**Comment by Cryostrixx** [comment]
> I am not sure if it is the fault of this PR, but when removing my powershell just stops working. terminal.exe, pwsh.exe and powershell.exe... even if running as admin. An invisible window will appear if starting powershell / pwsh directly without terminal for a second before closing again
> 
> image

Interesting... I have never seen this before, and as far as I know, it is not caused by this PR.
Can you provide the following information for me?
* Your Windows Version
* Your PowerShell version
* The version of WinUtil you ran.
* And any errors you got.

**Comment by MyDrift-user** [comment]
image
image

**Comment by Cryostrixx** [comment]
> image image I used the compiled version of this PR Did not get any error, looked fine

Since it appears you can't run PowerShell, can you open Command Prompt as admin and run these two commands?
* `dism /online /cleanup-image /restorehealth`
* `sfc /scannow`
-----
Once they are complete, please share the results.
While you are doing that I will match your software version so I can test it in an environment close to yours.

**Comment by MyDrift-user** [comment]
did a bit more testing and I think I know why. (this is the first and only time it did that to me)
it does not open at all, exept if you restart your devide, terminal gives me the error that the nerd font could not have been found

**Comment by Cryostrixx** [comment]
> did a bit more testing and I think I know why. (this is the first and only time it did that to me) it does not open at all, exept if you restart your devide, terminal gives me the error that the nerd font could not have been found.

The issue with Nerd Fonts is normal, I added a condition for it so that it will let the user know it was not found during the uninstallation, I don't know why but sometimes it just doesn't get installed (or uninstalled) correctly, it'll pop up a bunch of dialogs asking to replace a font file but it won't install.
Still, you might want to check for system corruption with those commands I shared as a bad update can easily cause rendering issues with UWP apps like Windows Terminal.

**Comment by Cryostrixx** [comment]
Hello, @MyDrift-user! Just to let you know I did test it again with a version closer to yours (Windows 11 Home 24H2, PowerShell 7.4.6) and it does not appear to be reproducible, leading me to believe it is a Windows bug that causes the invisible PowerShell windows; likely due to corrupted system files or a bad Windows update:
Here are the screenshots of it running in all four environments (PS5 and PS7 with and without Windows Terminal):
WinUtil_PS5_NoWT
WinUtil_PS7_NoWT
WinUtil_PS5_WT
WinUtil_PS7_WT

**Pull request closed without merging**
