### PR TITLE
Microwin and fixes

### LINKED ISSUE #1121: Support small resolutions
**Describe the bug**
On small screen resolutions, the winutils window opens too high up which puts the title bar off screen.

**To Reproduce**
1. Go to `System > Display` in `Settings`.
2. Decrease `Display resolution`. (Mine is `1366 x 768`)
3. Launch winutil

**Expected behavior**
Because the window is responsive and does scale, the best option would be to start it maximized (at least on small screens).
Another option would be to clamp the starting position to prevent it from going off-screen.
fullscreen winutil

**Screenshots**
winutil windows is too large

### LINKED ISSUE #1130: Please add scroll ability to Windows
I'm using a low res, 19" monitor, I noticed that in the Install Tab, the program names are small and I can't reach the bottom of the list.

Please make the font size constant across tabs and add a scrolling ability

I don't know if this is a limitation of the PowerShell script that I'm using or if this is also present in the .exe file

### PR DESCRIPTION
**Pull request by KonTy**
@ChrisTitusTech I found some time this evening to work on this. Wow that was a nasty merge took me hours to figure out XAML conflicts. Now everything is working fine. Here are some highlights:

1. Improved dark theme a bit, removed thick ugly borders on buttons
2. Selected tab stays selected :)
3. Tabs glow when you hover over them to indicate where you are
4. Ctrl-F allows you to seach tweaks and Apps
5. Fixed Icon now it looks like CTT logo now PowerShell
6. Added a scroll bar to support smaller screens (Fix #1130)
7. Shortcut keys Alt-I,T,C,I,M to navigate between tabs
8. Snap to top of the screen on start up (Fix #1121)
9. Added scrollbar and removed viewbox (Fix #1121)
10. Microwin feature -- create Windows 10,11 ISO without bloat

Give is a spin from my branch:

`irm https://raw.githubusercontent.com/KonTy/winutil/test-2023-11-15/winutil.ps1 | iex`

### CODE REVIEW

**Review by ChrisTitusTech — APPROVED** [review]

**Review by ChrisTitusTech — APPROVED** [review]

**Comment by ChrisTitusTech** [comment]
A fantastic start and the GUI improvements are extremely good. MicroWin will need a few tweaks like better checking for oscdimge.exe I see choco trying to grab it on my system and then failing to launch it after choco installs the Windows ADK. I'll have to troubleshoot why my system bombs out on that part, but the code looks good. I might tweak the popup prompts for the oscdimge check.

**Comment by Joly0** [comment]
Hey, i just tested this with a normal windows 11 iso downloaded through the microsoft website and i am getting quite alot of errors. Is there anywhere i can post them? I cant paste them here, as there are really a lot of errors

**Comment by Joly0** [comment]
I am just going to paste a bit here:
```
c:\microwinscratch\Program Files\Windows Media Player\de-DE\wmplayer.exe.mui: Zugriff verweigert                                                                                                                        c:\microwinscratch\Program Files\Windows Media Player\de-DE\WMPMediaSharing.dll.mui: Zugriff verweigert                                                                                                                 c:\microwinscratch\Program Files\Windows Media Player\de-DE\wmpnetwk.exe.mui: Zugriff verweigert                                                                                                                        c:\microwinscratch\Program Files\Windows Media Player\de-DE\wmpnscfg.exe.mui: Zugriff verweigert                                                                                                                        c:\microwinscratch\Program Files\Windows Media Player\de-DE\wmpnssci.dll.mui: Zugriff verweigert                                                                                                                        c:\microwinscratch\Program Files\Windows Media Player\de-DE\wmpnssui.dll.mui: Zugriff verweigert                                                                                                                        c:\microwinscratch\Program Files\Windows Media Player\Media Renderer\avtransport.xml: Zugriff verweigert                                                                                                                c:\microwinscratch\Program Files\Windows Media Player\Media Renderer\connectionmanager_dmr.xml: Zugriff verweigert                                                                                                      c:\microwinscratch\Program Files\Windows Media Player\Media Renderer\DMR_120.jpg: Zugriff verweigert                                                                                                                    c:\microwinscratch\Program Files\Windows Media Player\Media Renderer\DMR_120.png: Zugriff verweigert                                                                                                                    c:\microwinscratch\Program Files\Windows Media Player\Media Renderer\DMR_48.jpg: Zugriff verweigert                                                                                                                     c:\microwinscratch\Program Files\Windows Media Player\Media Renderer\DMR_48.png: Zugriff verweigert                                                                                                                     c:\microwinscratch\Program Files\Windows Media Player\Media Renderer\RenderingControl.xml: Zugriff verweigert                                                                                                           c:\microwinscratch\Program Files\Windows Media Player\Media Renderer\RenderingControl_DMP.xml: Zugriff verweigert                                                                                                       c:\microwinscratch\Program Files\Windows Media Player\Network Sharing\ConnectionManager.xml: Zugriff verweigert                                                                                                         c:\microwinscratch\Program Files\Windows Media Player\Network Sharing\ContentDirectory.xml: Zugriff verweigert                                                                                                          c:\microwinscratch\Program Files\Windows Media Player\Network Sharing\MediaReceiverRegistrar.xml: Zugriff verweigert                                                                                                    c:\microwinscratch\Program Files\Windows Media Player\Network Sharing\wmpnss_color120.jpg: Zugriff verweigert                                                                                                           c:\microwinscratch\Program Files\Windows Media Player\Network Sharing\wmpnss_color120.png: Zugriff verweigert                                                                                                           c:\microwinscratch\Program Files\Windows Media Player\Network Sharing\wmpnss_color32.bmp: Zugriff verweigert                                                                                                            c:\microwinscratch\Program Files\Windows Media Player\Network Sharing\wmpnss_color32.jpg: Zugriff verweigert                                                                                                            c:\microwinscratch\Program Files\Windows Media Player\Network Sharing\wmpnss_color48.bmp: Zugriff verweigert                                                                                                            c:\microwinscratch\Program Files\Windows Media Player\Network Sharing\wmpnss_color48.jpg: Zugriff verweigert                                                                                                            c:\microwinscratch\Program Files\Windows Media Player\Network Sharing\wmpnss_color48.png: Zugriff verweigert                                                                                                            c:\microwinscratch\Program Files\Windows Media Player\Skins\Revert.wmz: Zugriff verweigert                                                                                                                              Remove-Item : Cannot remove item C:\microwinscratch\Program Files\Windows Media Player\de-DE\mpvis.dll.mui: Access to the path is denied.                                                                               At C:\Users\julian\Downloads\winutil-test-2023-11-15\winutil.ps1:1099 char:4                                                                                                                                            +             Remove-Item -Force -Recurse "$($itemToDelete)"                                                                                                                                                            +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                + CategoryInfo          : InvalidArgument: (mpvis.dll.mui:FileInfo) [Remove-Item], ArgumentException                                                                                                                    + FullyQualifiedErrorId : RemoveFileSystemItemArgumentError,Microsoft.PowerShell.Commands.RemoveItemCommand                                                                                                         Remove-Item : Cannot remove item C:\microwinscratch\Program Files\Windows Media Player\de-DE\setup_wm.exe.mui: Access to the path is denied.                                                                            At C:\Users\julian\Downloads\winutil-test-2023-11-15\winutil.ps1:1099 char:4                                                                                                                                            +             Remove-Item -Force -Recurse "$($itemToDelete)"                                                                                                                                                            +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                + CategoryInfo          : InvalidArgument: (setup_wm.exe.mui:FileInfo) [Remove-Item], ArgumentException                                                                                                                 + FullyQualifiedErrorId : RemoveFileSystemItemArgumentError,Microsoft.PowerShell.Commands.RemoveItemCommand                                                                                                         Remove-Item : Cannot remove item C:\microwinscratch\Program Files\Windows Media Player\de-DE\wmlaunch.exe.mui: Access to the path is denied.                                                                            At C:\Users\julian\Downloads\winutil-test-2023-11-15\winutil.ps1:1099 char:4                                                                                                                                            +             Remove-Item -Force -Recurse "$($itemToDelete)"                                                                                                                                                            +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                + CategoryInfo          : InvalidArgument: (wmlaunch.exe.mui:FileInfo) [Remove-Item], ArgumentException                                                                                                                 + FullyQualifiedErrorId : RemoveFileSystemItemArgumentError,Microsoft.PowerShell.Commands.RemoveItemCommand                                                                                                         Remove-Item : Cannot remove item C:\microwinscratch\Program Files\Windows Media Player\de-DE\wmplayer.exe.mui: Access to the path is denied.                                                                            At C:\Users\julian\Downloads\winutil-test-2023-11-15\winutil.ps1:1099 char:4                                                                                                                                            +             Remove-Item -Force -Recurse "$($itemToDelete)"                                                                                                                                                            +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                + CategoryInfo          : InvalidArgument: (wmplayer.exe.mui:FileInfo) [Remove-Item], ArgumentException                                                                                                                 + FullyQualifiedErrorId : RemoveFileSystemItemArgumentError,Microsoft.PowerShell.Commands.RemoveItemCommand                                                                                                         Remove-Item : Cannot remove item C:\microwinscratch\Program Files\Windows Media Player\de-DE\WMPMediaSharing.dll.mui: Access to the path is denied.                                                                     At C:\Users\julian\Downloads\winutil-test-2023-11-15\winutil.ps1:1099 char:4                                                                                                                                            +             Remove-Item -Force -Recurse "$($itemToDelete)"                                                                                                                                                            +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                + CategoryInfo          : InvalidArgument: (WMPMediaSharing.dll.mui:FileInfo) [Remove-Item], ArgumentException                                                                                                          + FullyQualifiedErrorId : RemoveFileSystemItemArgumentError,Microsoft.PowerShell.Commands.RemoveItemCommand                                                                                                         Remove-Item : Cannot remove item C:\microwinscratch\Program Files\Windows Media Player\de-DE\wmpnetwk.exe.mui: Access to the path is denied.                                                                            At C:\Users\julian\Downloads\winutil-test-2023-11-15\winutil.ps1:1099 char:4                                                                                                                                            +             Remove-Item -Force -Recurse "$($itemToDelete)"                                                                                                                                                            +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                + CategoryInfo          : InvalidArgument: (wmpnetwk.exe.mui:FileInfo) [Remove-Item], ArgumentException                                                                                                                 + FullyQualifiedErrorId : RemoveFileSystemItemArgumentError,Microsoft.PowerShell.Commands.RemoveItemCommand
```

```
Fehler: Ungültige Syntax. Der Wert 'Y' kann für die Option '/d' nicht verwendet werden.                                                                                                                                 Geben Sie "TAKEOWN /?" ein, um die Syntax anzuzeigen.                                                                                                                                                                   c:\microwinscratch\Windows\System32\LogFiles\WMI\RtBackup\*: Zugriff verweigert                                                                                                                                         Fehler: Ungültige Syntax. Der Wert 'Y' kann für die Option '/d' nicht verwendet werden.                                                                                                                                 Geben Sie "TAKEOWN /?" ein, um die Syntax anzuzeigen.                                                                                                                                                                   c:\microwinscratch\Windows\System32\WebThreatDefSvc: Zugriff verweigert                                                                                                                                                 c:\microwinscratch\Windows\System32\WebThreatDefSvc\*: Zugriff verweigert                                                                                                                                               Fehler: Ungültige Syntax. Der Wert 'Y' kann für die Option '/d' nicht verwendet werden.                                                                                                                                 Geben Sie "TAKEOWN /?" ein, um die Syntax anzuzeigen.
Fehler: Ungültige Syntax. Der Wert 'Y' kann für die Option '/d' nicht verwendet werden.
Geben Sie "TAKEOWN /?" ein, um die Syntax anzuzeigen.
c:\microwinscratch\Windows\System32\LogFiles\WMI\RtBackup: Zugriff verweigert
c:\microwinscratch\Windows\System32\LogFiles\WMI\RtBackup\*: Zugriff verweigert
Fehler: Ungültige Syntax. Der Wert 'Y' kann für die Option '/d' nicht verwendet werden.
Geben Sie "TAKEOWN /?" ein, um die Syntax anzuzeigen.
c:\microwinscratch\Windows\System32\WebThreatDefSvc: Zugriff verweigert
c:\microwinscratch\Windows\System32\WebThreatDefSvc\*: Zugriff verweigert
Fehler: Ungültige Syntax. Der Wert 'Y' kann für die Option '/d' nicht verwendet werden.
Geben Sie "TAKEOWN /?" ein, um die Syntax anzuzeigen.
                                                                                                                                                                                                                         Removing Items                                                                                                                                                                                                             Deleteing C:\microwinscratch\Windows\SystemApps\microsoft.windows.narratorquickstart_8wekyb3d8bbwe                                                                                                                      [                                                                                                                                                                                                            ]                                                                                                                                                                                                                              Fehler: Ungültige Syntax. Der Wert 'Y' kann für die Option '/d' nicht verwendet werden.
Geben Sie "TAKEOWN /?" ein, um die Syntax anzuzeigen.
c:\microwinscratch\Windows\System32\WebThreatDefSvc: Zugriff verweigert
c:\microwinscratch\Windows\System32\WebThreatDefSvc\*: Zugriff verweigert
Administrators: Zuordnungen von Kontennamen und Sicherheitskennungen wurden nicht durchgeführt.
Remove-Item : Cannot remove item C:\microwinscratch\Windows\System32\OneDriveSetup.exe: Access to the path is denied.
At C:\Users\julian\Downloads\winutil-test-2023-11-15\winutil.ps1:1107 char:4
+             Remove-Item -Force "$($itemToDelete)"
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (C:\microwinscra...eDriveSetup.exe:FileInfo) [Remove-Item], ArgumentException
    + FullyQualifiedErrorId : RemoveFileSystemItemArgumentError,Microsoft.PowerShell.Commands.RemoveItemCommand
Fehler: Ungültige Syntax. Der Wert 'Y' kann für die Option '/d' nicht verwendet werden.
Geben Sie "TAKEOWN /?" ein, um die Syntax anzuzeigen.
c:\microwinscratch\Windows\System32\LogFiles\WMI\RtBackup: Zugriff verweigert
c:\microwinscratch\Windows\System32\LogFiles\WMI\RtBackup\*: Zugriff verweigert
Fehler: Ungültige Syntax. Der Wert 'Y' kann für die Option '/d' nicht verwendet werden.
Geben Sie "TAKEOWN /?" ein, um die Syntax anzuzeigen.
c:\microwinscratch\Windows\System32\WebThreatDefSvc: Zugriff verweigert
c:\microwinscratch\Windows\System32\WebThreatDefSvc\*: Zugriff verweigert
Administrators: Zuordnungen von Kontennamen und Sicherheitskennungen wurden nicht durchgeführt.
```
So its basically a lot of "permission denied" errors

**Comment by KonTy** [comment]
@Joly0 it seems related to the fact that you are on a machine with German local. see takeown.exe you supply default answer using
/d follow by answer in English it's obviously Y for Yes
takeown /a /r **/d Y** /f 

Let me look at how to make it respect different locals.

**Comment by Joly0** [comment]
Yes, you are 100% right, this should be the cause of this issue. Hopefully this is not too difficult to fix. But i think its good, that this was tested before going live on a system with different language. 

Cmd and commands that are based on it often handle those multi-language things very badly imo. Powershell is highly superior in this regard, atleast from my experience

**Comment by Joly0** [comment]
Yes, you are 100% right, this should be the cause of this issue. Hopefully this is not too difficult to fix. But i think its good, that this was tested before going live on a system with different language. 

Cmd and commands that are based on it often handle those multi-language things very badly imo. Powershell is highly superior in this regard, atleast from my experience

**Comment by KonTy** [comment]
Let me look if this can be done in powershell native. That would be even better if we don't have to call out to any exe.

**Comment by KonTy** [comment]
> Yes, you are 100% right, this should be the cause of this issue. Hopefully this is not too difficult to fix. But i think its good, that this was tested before going live on a system with different language.
> 
> Cmd and commands that are based on it often handle those multi-language things very badly imo. Powershell is highly superior in this regard, atleast from my experience
> 
> Edit: I looked through your changes and didnt see any use of takeown?

Submitted a fix: https://github.com/ChrisTitusTech/winutil/pull/1185

**Pull request merged**
