### PR TITLE
Config file validation

### PR DESCRIPTION
**Pull request by EmilyGraceSeville7cf**
## Type of Change
- [x] New feature
- [ ] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
Provides completion and validation for some config files in a JSON format.

Features:

- JSON schemas:
  - [x] applications.json ([schema source](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/winutil-applications.json))
  - [x] preset.json ([schema source](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/winutil-presets.json))
  - [ ] themes.json
- CI:
  - [ ] config validation

image

## Testing
Testing has been performed in SchemaStore project.

## Issue related to PR

- Resolves #

## Additional Information
VS Code code pulls schemas from a [SchemaStore](https://github.com/SchemaStore/schemastore) schema catalog in the background
according to **.vscode/settings.json** file and provides completion and
validation.

## Checklist
- [ ] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by Real-MullaC** [comment]
How does this work?

**Comment by EmilyGraceSeville7cf** [comment]
> How does this work?

It checks whether config files match the structure of the JSON schema. And if they do not, VS Code reports errors. Also, if a user presses `Ctrl+Spaces` possible key values are suggested. 😄

**Comment by Real-MullaC** [comment]
Make sure to update docs for if this is merged so people know.

**Comment by Marterich** [comment]
Does this mean, winutil will become dependent on the third-party Github Repo SchemaStore for Autocompletion (e.g. If we want to add to the Schema[autocompletion], we are at the mercy of the Maintainer of SchemaStore to merge the Update PR) or am I missing something here? 
I don't know how to feel about this...

**Comment by 4yman-0** [comment]
>winutil will become dependent on the third-party Github Repo SchemaStore for Autocompletion

Can we add files somewhere in the repo instead of hosting it on SchemaStore?

**Comment by EmilyGraceSeville7cf** [comment]
> Does this mean, winutil will become dependent on the third-party Github Repo SchemaStore for Autocompletion (e.g. If we want to add to the Schema[autocompletion], we are at the mercy of the Maintainer of SchemaStore to merge the Update PR) or am I missing something here?
I don't know how to feel about this...

In the current implementation id does. But the way this completion is provided *can be changed*: I can put such schemas right here, in this repository. It worth to note that I've just placed schemas to SchemaStore initially because I'm relatively well-known contributor there and my PRs are relatively quickly accepted. 😄 However, I share your feelings about SchemaStore. And I'll move schemas here.

> Can we add files somewhere in the repo instead of hosting it on SchemaStore?

Yes, we can. It's technically possible. I just have to put schemas here and map them to validated JSON files (like I did with remote schemas).

**Comment by ruxunderscore** [comment]
I like this idea. Can wait to see what other changes you bring. I'd like to see what you do with themes.json.

**Comment by MyDrift-user** [comment]
I think this was aleady tried out once with a local scheme in #2532 and closed out. Correct me if I'm wrong or did not understand it.

**Pull request closed without merging**
