### PR TITLE
support for applying tweaks with cli

### PR DESCRIPTION
**Pull request by YoraiLevi**
#51 
botched support for applying tweaks with cli needs more work for confirm and whatif flags.
`.\winutil.ps1 -Tweaks 'WPFEssTweaksDeleteTempFiles`

will work on that later this week, i have an exam.

### CODE REVIEW

**Comment by DeveloperDurp** [comment]
One thing to keep in mind is how the script is executed, when you pipe the script to an Invoke-expression (IEX) you loose the ability to add parameters to the script how you normally would with a local script.

**Comment by YoraiLevi** [comment]
> One thing to keep in mind is how the script is executed, when you pipe the script to an Invoke-expression (IEX) you loose the ability to add parameters to the script how you normally would with a local script.

In the past I faced that exact issue and came up with a solution in the readme here, https://github.com/YoraiLevi/ansible_playbooks 
basically
```
Invoke-Command $([Scriptblock]::Create(($code) -join "`r`n")) -ArgumentList $playbook
```
converts the raw script into an executable code block and then execute it with the arguments provided.

**Comment by blusewill** [comment]
As a reminder you have been Pull Requested to wrong branch
it's should be `2023-09-23-test`

**Comment by DeveloperDurp** [comment]
> > One thing to keep in mind is how the script is executed, when you pipe the script to an Invoke-expression (IEX) you loose the ability to add parameters to the script how you normally would with a local script.
> 
> In the past I faced that exact issue and came up with a solution in the readme here, https://github.com/YoraiLevi/ansible_playbooks basically
> 
> ```
> Invoke-Command $([Scriptblock]::Create(($code) -join "`r`n")) -ArgumentList $playbook
> ```
> 
> converts the raw script into an executable code block and then execute it with the arguments provided.

While that might work it will make starting winutil slightly more difficult for non power users. 

If you look at this line it shows you what we were looking to do
https://github.com/ChrisTitusTech/winutil/blob/b33b5c94b3002264adab505162ec13ad9eb47a26/runspace.ps1#L1417

https://github.com/ChrisTitusTech/winutil/pull/52

**Comment by ChrisTitusTech** [comment]
While I like the idea, the execution for this project would over complicate it. The better solution would be just to have a CLI fork that executes a ps1 file with no XAML or GUI. If people really want this I'd probably look at ways of having it pull the JSON from the official project during compilation and execute that way so both would update each other. 
I'm going to close this PR for now as I don't want to explore this type of expansion on the project right now.

**Comment by YoraiLevi** [comment]
If someone needs some basic implementations for cli; beware that tweaks that use winget may require interaction as in the gui.
```
Invoke-WebRequest https://raw.githubusercontent.com/YoraiLevi/winutil_tweaks_cli/master/winutil_cli.ps1 -OutFile winutil_cli.ps1
winutil_cli.ps1 -TweakNames WPFBingSearch,WPFEssTweaksAH,WPFEssTweaksDeBloat,WPFEssTweaksDeleteTempFiles,WPFEssTweaksDiskCleanup,WPFEssTweaksDVR,WPFEssTweaksHiber,WPFEssTweaksHome,WPFEssTweaksLoc,WPFEssTweaksOO,WPFEssTweaksRemoveEdge,WPFEssTweaksRemoveOnedrive,WPFEssTweaksServices,WPFEssTweaksStorage,WPFEssTweaksTele,WPFEssTweaksWifi,WPFMiscTweaksDisableipsix,WPFMiscTweaksDisableMouseAcceleration,WPFMiscTweaksDisableNotifications,WPFMiscTweaksDisableUAC,WPFMiscTweaksDisplay,WPFMiscTweaksEnableipsix,WPFMiscTweaksEnableMouseAcceleration,WPFMiscTweaksEnableVerboselogon,WPFMiscTweaksExt,WPFMiscTweaksLapNum,WPFMiscTweaksNum,WPFMiscTweaksRightClickMenu,WPFMiscTweaksUTC -WindowsFeaturesBundles WPFFeaturenfs,WPFFeaturesdotnet,WPFFeatureshyperv,WPFFeatureslegacymedia,WPFFeaturewsl
```

**Comment by YoraiLevi** [comment]
I don't think this matters too much, I have implemented the most important functionality into my cli script and it automatically fetches most recent configuration.

it needs some test to make sure it doesn't break though.
contributions and forks are welcome.

**Comment by YoraiLevi** [comment]
Pleae open an issue at my repo :)

**Pull request closed without merging**
