### PR TITLE
HotFix for intel hd

### PR DESCRIPTION
**Pull request by YusufKhalifadev**
# Pull Request
fixed low performance on intel hd
## Title
intel hd graphics too slow on winutil

## Type of Change
- [ ] New feature
- [X] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [X] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
winutil was too slow on intel hd graphics

## Testing
I tested it on my PC 

## Impact
fix this issue for intel hd users

## Checklist
- [X] My code adheres to the coding and style guidelines of the project.
- [X] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [X] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Review by Real-MullaC — APPROVED** [review]

**Comment by MyDrift-user** [comment]
hello @YusufKhalifadev, thanks for this PR
How about changing `"*UHD*"` to `"*HD*"`, this way both would be integraded in the logic while keeping it short and making sure everything with HD in it also get's added.

**Comment by YusufKhalifadev** [comment]
@MyDrift-user thanks for reporting sure we'll add it

**Comment by og-mrk** [comment]
> hello @YusufKhalifadev, thanks for this PR
> How about changing `"*UHD*"` to `"*HD*"`, this way both would be integraded and keep it short, that way it is making sure everything where HD gets mentioned also get's added.

It might falsely detect Radeon HD graphics cards as low spec.. even though it should handle the GUI efrects quite well.

Leaving it with the current changes proposed by this PR is better, IMHO.

**Comment by MyDrift-user** [comment]
> Leaving it with the current changes proposed by this PR is better, IMHO.
don't really know about Radeon GPUs, but thanks for the imput.
@YusufKhalifadev, I suggest not doing the changes I've mentioned.

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
