### PR TITLE
[MicroWin] Add custom user settings and other changes (docs/bugfixes)

### PR DESCRIPTION
**Pull request by CodingWonders**
# Pull Request

## Title
(Same as title)

## Type of Change
- [X] New feature
- [X] Bug fix
- [X] Documentation update
- [X] UI/UX improvement

## Description
Some people on the Discord community had suggested the ability to configure a custom user, and that's what this PR is (mainly) about.

Result with empty values:

powershell_XLDCCdeMZj
notepad_GAvmxRMUoG

Result with custom values:

1SqchB9Sld
notepad_TMrmibkxmy

It also adds checks for expedited app removal to prevent it from throwing REG errors

## Testing
Testing concluded with custom users being reflected in the target unattended answer file

## Impact
Custom user accounts

## Issue related to PR
None (suggestion on Discord)

## Additional Information
None, apart from slight changes in documentation

## Checklist
- [X] My code adheres to the coding and style guidelines of the project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Comment by zmileski** [comment]
I think best user experience is just don't specify <User Accounts> in unattended and bypass oobe=true will ask only about User and Password. I tested so many times and it works.

**Comment by CodingWonders** [comment]
@zmileski, it's become harder to configure a local account interactively in Windows 11 version 24H2 onwards. It now requires a Microsoft account; the only way to pass it is to turn off the network adapters.

Here is a test run with interactive account settings on the latest Dilithium build (build 27686):

DT PE (with HDD)-2024-08-19-14-55-18

DT PE (with HDD)-2024-08-19-14-55-44

DT PE (with HDD)-2024-08-19-14-56-12

DT PE (with HDD)-2024-08-19-14-57-59

**Comment by ChrisTitusTech** [comment]
@zmileski Microsoft has other ideas interactive will not work any longer for local accounts.

Thank you @CodingWonders for this as it is exactly what I had in mind.

**Review by ChrisTitusTech — APPROVED** [review]

**Comment by zmileski** [comment]
Just tested on build 27686 with https://schneegans.de/windows/unattend-generator/ oobe was bypasset and only in the end asked me to enter user and password and was online during setup




what i used in unattend
Bypass Windows 11 requirements check (TPM, Secure Boot, etc.)
Allow Windows 11 to be installed without internet connection
Add user accounts interactively during Windows Setup
Skip Wi-Fi configuration

**Comment by CodingWonders** [comment]
The same settings were applied in my test case. Translated to the DT Language:

VTpD8wi5sc

DISMTools_XvEI5JUmXl

DISMTools_GV4dFBfkRe

@zmileski, so that is weird. Could it be VirtualBox?

**Comment by zmileski** [comment]
Yes maybe it is with network on virtual box
Tested now on real mahine and yes to set up local account needed to choose for organisation instead for personal use.
You are right the only way to do is offline.

**Comment by CodingWonders** [comment]
Some people have reported that the target image doubles in size. I'm investigating this issue to see what exactly is causing the issue.

Please wait for updates on this issue

**Pull request merged**
