### PR TITLE
Update applications.json - Added NDI Tools

### PR DESCRIPTION
**Pull request by tvrepairguy**
NDI, or Network Device Interface, is developed by Newtek. It enables the encoding, transmission, and reception of high-quality, low latency, video and audio over IP. 

https://ndi.video/

### CODE REVIEW

**Comment by blusewill** [comment]
Hmm this is weird PR. Why you edited so many files?

**Comment by og-mrk** [comment]
Hello @tvrepairguy, your PR is pointing (or "wanting to merge") into the wrong the branch ([main](https://github.com/ChrisTitusTech/winutil/tree/main)), please change it to the current test branch ([test-2024-04-20-2](https://github.com/ChrisTitusTech/winutil/tree/test-2024-04-20-2))

**Comment by tvrepairguy** [comment]
My bad, first time trying to do this

**Comment by og-mrk** [comment]
> My bad, first time trying to do this

no, it's ok @tvrepairguy 😄

Now I did notice that you've deleted your own branch (the branch which has your actual changes that you want to merge), which is not exactly what I meant, I should've provided a link to the docs in that comment, so my bad.

if you're confused about something (which is specific to This Project), then feel free to ask, _but_ if it's a general thing/feature in GitHub that you may not fully understand, then searching online and looking through [GitHub Docs](https://docs.github.com/) will help alot in learning how to use GitHub Features, and some of Git documents here and there (Git is tool which does Version Control, the "Back-Bone" of every Git Repository on GitHub)

for this particular case, first and foremost, restore your branch that you've previously deleted, then you'll need to change the base branch (the branch which your PR targets) to the correct one, which's ChrisTitusTech's Test Branch, to do so, please follow the steps documented on [this page by GitHub](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request).

if you've done the explanation above, and still having trouble, then you can always make a new branch on your fork, make your changes in that new branch, then make a new PR with the correct base branch set (The test branch), so it'll be `YourNewBranch -> test-2024-04-20-2`.

Hope my comment helped, if your stuck in any part, _then like I've said before_, GitHub Docs is an incredible resource, and if you find the UI for it a bit confusing, you can look online for How To(s) using Google, Brave, DuckDuckGo (or any other search engine), and if you use a Search Engine correctly, you'll find the correct page really quick 😎

**Comment by tvrepairguy** [comment]
Thanks for the help and for the links. I'll be sure to check it out.

**Pull request closed without merging**
