### PR TITLE
Debloat Edge Tweak

### PR DESCRIPTION
**Pull request by MyDrift-user**
# Pull Request

## Type of Change
- [x] New feature

## Description
A better way of dealing with Edge than uninstalling it and breaking your OS, you can also debloat it to not be that shitty as stock. This will be for people like me that have to work with edge due to work reasons.

Features:
- Disables multiple Popups, full screen popups where u can't even close edge, first startup popup (window overtaking bullcrap)...
- Remove some telemetry (sending every opened webpage to bing api, image telemetry...)
- Disable Edge from creating a Desktop Shortcut after updates
- more stuff that noone needs

Based on [this](https://gist.github.com/yashgorana/83a2939d739e312820f39703fe991412), but did not use all of it.

## Testing
Testet it on my machine & Sandbox, works fine.

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Review by Real-MullaC — APPROVED** [review]

**Comment by YusufKhalifadev** [comment]
@MyDrift-user this maybe doesn't work at least for me I don't find these registry keys on my system although I have edge installed so maybe there's another way-around

**Comment by MyDrift-user** [comment]
Hey @YusufKhalifadev 
Thanks for reporting, these are group policy keys. As far as I know they might not be there by default but should work on windows home&pro edition. Will test this further today with diffrent windows editions.

**Review by ChrisTitusTech — APPROVED** [review]

**Comment by ChrisTitusTech** [comment]
This will only work on Pro edition @MyDrift-user - I'm thinking about taking my updates section and using something like PolicyPlus https://github.com/Fleex255/PolicyPlus

**Comment by misraaks** [comment]
Does the "disable telemetry" tweak undo this tweak when it deletes HKLM\SOFTWARE\Policies\Microsoft\Edge?

**Comment by misraaks** [comment]
@MyDrift-user I believe you're right that this should also work on Home because you're just recreating the registry keys that Group Policy would otherwise create on Pro. 

I've been setting a lot of these keys manually but I find that the "Disable Telemetry" tweak undoes my manual changes because it deletes HKLM\SOFTWARE\Policies\Microsoft\Edge. Could that be what's happening to @YusufKhalifadev?

**Comment by ChrisTitusTech** [comment]
> @MyDrift-user I believe you're right that this should also work on Home because you're just recreating the registry keys that Group Policy would otherwise create on Pro.
> 
> I've been setting a lot of these keys manually but I find that the "Disable Telemetry" tweak undoes my manual changes because it deletes HKLM\SOFTWARE\Policies\Microsoft\Edge. Could that be what's happening to @YusufKhalifadev?

I've seen home editions ignore regedit policies. Specifically my update settings implement with this method. Sometime in the late Win10 cycle to Win11 releases they started ignoring policies on home.

**Comment by MyDrift-user** [comment]
> > @MyDrift-user I believe you're right that this should also work on Home because you're just recreating the registry keys that Group Policy would otherwise create on Pro.
> > I've been setting a lot of these keys manually but I find that the "Disable Telemetry" tweak undoes my manual changes because it deletes HKLM\SOFTWARE\Policies\Microsoft\Edge. Could that be what's happening to @YusufKhalifadev?
> 
> I've seen home editions ignore regedit policies. Specifically my update settings implement with this method. Sometime in the late Win10 cycle to Win11 releases they started ignoring policies on home.

That is sad to hear, does PolicyPlus provide support for third party policies? because Edge policies are usually not preinstalled and are added manually: https://www.microsoft.com/de-de/edge/business/download?form=MA13FJ (small text under download button)

**Pull request merged**
