### PR TITLE
Update applications.json (Added the FOSS QGIS Application) 

### PR DESCRIPTION
**Pull request by SnoepNFTs**
Added the FOSS QGIS Application https://qgis.org/en/site/

### CODE REVIEW

**Comment by ruxunderscore** [comment]
Probably better to put it in the "Utilities" or "Pro Tools" section, instead.

**Comment by SnoepNFTs** [comment]
> Probably better to put it in the "Utilities" or "Pro Tools" section, instead.

No, because it fits under neither of those sections. It is closer to being blender / OpenSCAD / FreeCAD than any programs listed under the sections you just mentioned.

**Comment by SnoepNFTs** [comment]
> Probably better to put it in the "Utilities" or "Pro Tools" section, instead.

Thanks very much for that last-minute unnecessary question BTW. I am sure its going to take another 3 weeks to finally get my PR merged in.

**Comment by ruxunderscore** [comment]
I understand what you mean, but you don't have to get passive aggressive. Chris was on vacation and just got to sit down last night and look at the PRs. He only held back on this one , as he didn't know what QGIS was and was tired.

**Comment by SnoepNFTs** [comment]
> I understand what you mean, but you don't have to get passive aggressive. Chris was on vacation and just got to sit down last night and look at the PRs. He only held back on this one , as he didn't know what QGIS was and was tired.

Yeah, I agree. Looking back, I regret sending that last comment. Sorry, my friend. I had a terrible day, but that's no excuse.

**Review by ChrisTitusTech — APPROVED** [review]

**Pull request merged**
